### ISSUE TITLE
A bug in utils/tificc.c ?

### ISSUE THREAD

**Issue by atomer2** [mm2/Little-CMS#103]
When input image and output image  are both PLANARCONFIG_SEPARATE, they might have different number of planes , such as RGB as input and CMYK as output, but in function StripBasedXform and TileBasedXform ,  a parameter "nPlanes"  is used to represent the number of planes of input image and output image ,thus the numbers are always the same, is this a bug?

**Comment by mm2** [comment]
Thanks for reporting. Currently, planar tiffs are not supported and this code is there as a placeholder for future growing. Lcms core does support planar, indeed.
