### ISSUE TITLE
Warnings from Visual Studio 2017 code analysis

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#107]
src\cmsgamma.c(1043): warning C6262: Function uses '49196' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
     src\cmsplugin.c(765): warning C6387: 'p' could be '0':  this does not adhere to the specification for the function 'CloseHandle'. 
     src\cmsplugin.c(955): warning C28182: Dereferencing NULL pointer. 'prev' contains the same NULL value as '_cmsContextPoolHead' did.

**Comment by mm2** [comment]
Thanks for reporting. This one is being also reported by VS2015, I think 
this is an analyzer bug:

> src\cmsplugin.c(955): warning C28182: Dereferencing NULL pointer. 'prev' contains the same NULL value as '_cmsContextPoolHead' did

This is the code

   for (prev = _cmsContextPoolHead;
                  prev != NULL;
                  prev = prev ->Next)
             {
                 if (prev -> Next == ctx) {
                     prev -> Next = ctx ->Next;
                     break;
                 }
             }


Regards
Marti

**Comment by mm2** [comment]
Now tried and goes fine (with the known false positives)

**Comment by boxerab** [comment]
Great, thanks.
