### ISSUE TITLE
integer overflow in FillFirstShaper()

### ISSUE THREAD

**Issue by kcwu** [mm2/Little-CMS#111]
When cmsEvalToneCurveFloat() return infinite value or `-Inf`, `DOUBLE_TO_1FIXED14()` will overflow when casting from double to int.
```
1557            y   = cmsEvalToneCurveFloat(Curve, R);
1558
1559            Table[i] = DOUBLE_TO_1FIXED14(y);
```

p.s. this is my https://github.com/mm2/Little-CMS/pull/108 trying to handle.

**Comment by mm2** [comment]
Now it is fixed with 
https://github.com/mm2/Little-CMS/commit/f4a958ec4a7623bf56a10ea46a9163d4bbcb6f64
