### ISSUE TITLE
DESTDIR and "remember to run `libtool --finish /usr/lib'"

### ISSUE THREAD

**Issue by version2013** [mm2/Little-CMS#113]
`gcc --version`
gcc (GCC) 4.2.2

Using DESTDIR when installing results in several warnings.

[quote]

`make DESTDIR=/opt/temp/lcms2-2.8 install`
Making install in src
make[1]: Entering directory `/opt/lcms2-2.8/src'
make[2]: Entering directory `/opt/lcms2-2.8/src'
 .././install-sh -c -d '/opt/temp/lcms2-2.8/usr/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/ginstall -c   liblcms2.la '/opt/temp/lcms2-2.8/usr/lib'
libtool: install: /usr/bin/ginstall -c .libs/liblcms2.so.2.0.8 /opt/temp/lcms2-2.8/usr/lib/liblcms2.so.2.0.8
libtool: install: (cd /opt/temp/lcms2-2.8/usr/lib && { ln -s -f liblcms2.so.2.0.8 liblcms2.so.2 || { rm -f liblcms2.so.2 && ln -s liblcms2.so.2.0.8 liblcms2.so.2; }; })
libtool: install: (cd /opt/temp/lcms2-2.8/usr/lib && { ln -s -f liblcms2.so.2.0.8 liblcms2.so || { rm -f liblcms2.so && ln -s liblcms2.so.2.0.8 liblcms2.so; }; })
libtool: install: /usr/bin/ginstall -c .libs/liblcms2.lai /opt/temp/lcms2-2.8/usr/lib/liblcms2.la
libtool: install: /usr/bin/ginstall -c .libs/liblcms2.a /opt/temp/lcms2-2.8/usr/lib/liblcms2.a
libtool: install: chmod 644 /opt/temp/lcms2-2.8/usr/lib/liblcms2.a
libtool: install: ranlib /opt/temp/lcms2-2.8/usr/lib/liblcms2.a
libtool: install: warning: remember to run `libtool --finish /usr/lib'

[/quote]

The command finishes installing lcms2 with additional warnings.

The libs are installed in the temp path directories, despite the warnings.

Does installing this way affect the functioning of lcms2 when compared to just using 'make install' or 'new2dir make install' ?

note: new2dir uses installwatch.

**Comment by mm2** [comment]
Hi, this is a known issue of autotools, see 
http://stackoverflow.com/questions/32766609/libtool-installation-issue-with-make-install
