### ISSUE TITLE
How to apply profile with PCS = cmsSigXYZData, Color Space = cmsSigGrayData  ?

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#117]
Hello,

I have a jpeg 2000 file with an ICC profile.

PCS is `cmsSigXYZData` and color space is `cmsSigGrayData`.

The file can be found here:  https://github.com/GrokImageCompression/grok/issues/38

I am working on a library that decodes the jpeg 2000 file and applies the ICC profile, using LCMS.

Currently, I have this code:

    in_type = TYPE_GRAY_8;
    out_type = TYPE_RGB_8;
    out_prof = cmsCreate_sRGBProfile();

and I can create the transform and apply the ICC profile, but the output is an RGB file.
What I would like is to output a grayscale file.

So, if I instead call

    out_prof = cmsCreateGrayProfile(NULL,NULL);

then `cmsCreateTransform`  returns NULL and I can't apply the profile.

What is the best way of creating a transform for this kind of grayscale image ?

Thanks so much,
Aaron

**Comment by mm2** [comment]
not an issue, cmsCreateGrayProfile(NULL,NULL) is not going to work because bad parameters.

**Comment by boxerab** [comment]
Thanks. Can you recommend a better way of doing this?

**Comment by boxerab** [comment]
Alright, will explore this issue further on user mailing list. Thanks.
