### ISSUE TITLE
Potential out of memory error

### ISSUE THREAD

**Issue by dj2** [mm2/Little-CMS#122]
Given a crafted input, it's possible to request lcms to allocate a lot more memory then it will need, potentially causing an OOM. The ReadPositiontable method can be updated to verify the amount of data available in the input is more then what will be needed to read before allocating the arrays and existing early if the input is bad.

A potential fix can be seen at: https://pdfium-review.googlesource.com/c/5110/  (https://pdfium.googlesource.com/pdfium/+/master/third_party/lcms2-2.6/0018-verify-size-before-reading.patch)

**Comment by mm2** [comment]
The fix looks great, thank you
