### ISSUE TITLE
Opening profiles with non-ASCII filename fails on Windows

### ISSUE THREAD

**Issue by houz** [mm2/Little-CMS#123]
Hello,

when trying to open a file with a filename in UTF8 using `cmsOpenProfileFromFile()` it fails. The reason is that `cmsOpenIOhandlerFromFile()` uses `fopen()` which doesn't support Unicode on Windows. There is `_wfopen()` though. See https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx for details.

**Comment by mm2** [comment]
please use cmsOpenProfileFromStream intead,  That is what this function is for. _wfopen is not portable.

**Comment by houz** [comment]
Of course it's not portable. That's the point. Instead of forcing every program that might get ported to Windows to special case for that, or not use `cmsOpenProfileFromFile()` at all I think it would be nice if lcms2 would just work everywhere by being able to open files even on Windows. Currently that doesn't work.

**Comment by mm2** [comment]
Just use cmsOpenProfileFromStream()

FILE *f = _wfopen("C:\\myweidfilename.icc", "rb");

if  (f == NULL) error...

h = cmsOpenProfileFromStream(f, "r");
