### ISSUE TITLE
Compilation errors on VS2012

### ISSUE THREAD

**Issue by pathcore-tasos** [mm2/Little-CMS#125]
The Visual Studio 2012 (MSVC 10) build of Little CMS fails to compile with the following errors:

`error LNK2019: unresolved external symbol _isinf referenced in function _EvalSegmentedFn	\path\to\Little-CMS\Projects\VC2012\psicc\lcms2_static.lib(cmsgamma.obj)	psicc
`

`error LNK2019: unresolved external symbol __cmsHandleExtraChannels referenced in function _CachedXFORM	\path\to\Little-CMS\Projects\VC2012\psicc\lcms2_static.lib(cmsxform.obj)	psicc
`

`LNK2019: unresolved external symbol _isnan referenced in function _fclamp	\path\to\Little-CMS\Projects\VC2012\psicc\lcms2_static.lib(cmsintrp.obj)	psicc
`
These errors are the result of undefined functions, like so:
`warning C4013: 'isnan' undefined; assuming extern returning int	\path\to\Little-CMS\src\cmsintrp.c	218	lcms2_static
`

It looks like there were a few backwards-incompatible changes in recent versions of Little CMS.

**Comment by XhmikosR** [comment]
I guess, this can be closed since https://github.com/mm2/Little-CMS/pull/127 is merged.

**Comment by mm2** [comment]
Right, it is fixed now
