### ISSUE TITLE
Query on CookPointers() method

### ISSUE THREAD

**Issue by ya1gaurav** [mm2/Little-CMS#130]
for (i=0; i < t -> nPatches; i++) {

                char *Data = GetData(it8, i, idField);
                if (Data) {
                    char Buffer[256];

                    strncpy(Buffer, Data, 255);
                    Buffer[255] = 0;

                    if (strlen(Buffer) <= strlen(Data))
                        strcpy(Data, Buffer);
                    else
                        SetData(it8, i, idField, Buffer);

                }
            }
What is this code trying to do?
Is it trying to remove characters at indexes >255 ?
If so, why to follow this complex code?
Just set all values of "data" after 255 as 0.

**Comment by mm2** [comment]
Fixed in 2.10 Thanks for reporting
