### ISSUE TITLE
Handling of negative numbers in DefaultEvalParametricFn

### ISSUE THREAD

**Issue by suzukihf** [mm2/Little-CMS#135]
LittleCMS returns a different value than Adobe CMM, but is it intended?
a*,b* becomes 0 without becoming negative.
It is not stipulated in ICC SpecV4.3.
Why this Code is necessary?

*******************
conditions
*******************
 DefaultEvalParametricFn(cmsgamma.c:312-568) in LittleCMS 2.8
 Profile:http://www.color.org/Probev2.zip
 Tag:D2B0(multiProcessElementsType Curve Set element) Processing
  Type 6(Y = (a * X + b) ^ Gamma + c), a=255.0, b=-128.0, Gamma=1.0, c=0.0
  * For L*a*b* 0.0-1.0 To 0.0...100.0(L*), -128...127(a*,b*)

*******************
Function
*******************
`DefaultEvalParametricFn()
{
    // Types 6,7,8 comes from segmented curves as described in ICCSpecRevision_02_11_06_Float.pdf
    // Type 6 is basically identical to type 5 without d

    // Y = (a * X + b) ^ Gamma + c
    case 6:
        e = Params[1]*R + Params[2];

        **if (e < 0)
            Val = Params[3];**
        else
            Val = pow(e, Params[0]) + Params[3];
        break;
}
`

**Comment by mm2** [comment]
There is no easy workaround as negative base of power function may result in complex numbers. I choose to force this cases to zero to prevent NaN exceptions. Probe profile is using negative numbers on pow and this may return different values on depending on the application.

**Comment by suzukihf** [comment]
OK.
Thank you for your answer.
