### ISSUE TITLE
undefined reference error in make check

### ISSUE THREAD

**Issue by bdubbs** [mm2/Little-CMS#138]
In lcms2-2.9 I am getting the same undefined references error reported in issue #79.

/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:577: undefined reference to `_cmsStageAllocIdentityCurves'
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:579: undefined reference to `_cmsStageAllocIdentityCurves'
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:590: undefined reference to `_cmsStageAllocIdentityCurves'
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:592: undefined reference to `_cmsStageAllocIdentityCurves'
testcms2.o: In function `CheckNamedColorLUT':
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:3521: undefined reference to `_cmsStageAllocNamedColor'
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:3521: undefined reference to `_cmsStageAllocNamedColor'
testcms2.o: In function `CheckLab2LabMatLUT':
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:3485: undefined reference to `_cmsStageAllocLab2XYZ'
/tmp/lcms2/lcms2-2.9/testbed/testcms2.c:3487: undefined reference to `_cmsStageAllocXYZ2Lab'

etc

**Comment by bdubbs** [comment]
I've figured out why this is happening, at least on linux.  Removing -fvisibility-hidden is needed,  I did it by commenting out the line in configure.ac that adds it to CFLAGS:

sed -i '/AX_APPEND/s/^/#/' configure.ac

Note that this is only a problem if trying to 'make check'.  Perhaps the checks should be updated to not use internal symbols.

**Comment by mm2** [comment]
Thanks for reporting. It is surprising travis does not detect that and also in my debian sandbox is working fine. So probably you are running make check on dynamic .so compilation. Could please confirm if this is the case? Thanks

**Comment by bdubbs** [comment]
Perhaps.  I did:

./configure --prefix=/usr --disable-static  &&
make
make check

**Comment by mm2** [comment]
Yep, that is... You uncovered a nasty bug, so many thanks!On Nov 11, 2017 18:07, bdubbs <notifications@github.com> wrote:Perhaps.  I did:
./configure --prefix=/usr --disable-static  &&
make
make check

**Comment by mm2** [comment]
fixed
