### ISSUE TITLE
SHA-256 mismatch for lcms2-2.9.tar.gz

### ISSUE THREAD

**Issue by ilovezfs** [mm2/Little-CMS#140]
Homebrew users currently cannot build little-cms2 from source due to a SHA-256 checksum mismatch for lcms2-2.9.tar.gz (https://downloads.sourceforge.net/project/lcms/lcms/2.9/lcms2-2.9.tar.gz)

Mon Nov 6 12:22:52 2017 -0800 the checksum was
00756bed09ce059a68289f10de56b00267667647393ddc30400cb87c0d9037d5

On Nov 14 (reported to Homebrew here: https://github.com/Homebrew/homebrew-core/issues/20628) it became
40bf6bedc2836c673bf2fd5a0f24a696f789b394b2fbed043128366c6d75a5b8

And now it's changed again:
d4ad6f8718f7f9dc8b2a3276c9f237aa3f5eccdcf98b86dedc4262d8a1e7f009

Do you have any idea what happened here? To rule out malicious circumstances, we'll need to know why the file has changed, now twice, before the checksum can be updated in Homebrew. Thanks!

CC @mm2

**Comment by mm2** [comment]
Why are you using this tarball?
This is NOT an official release, current version is 2.8, please see http://www.littlecms.com/download.html

**Comment by ilovezfs** [comment]
@mm2 because https://sourceforge.net/projects/lcms/ shows 2.9 as the current version.

**Comment by mm2** [comment]
I see. sourceforge is used by lcms as a way to store files only. Please don't relay on sourceforce for tracking releases. I'm removing the offending files. Thanks for reporting.

**Comment by ilovezfs** [comment]
@mm2 Thanks for the help. I'll force downgrade the Homebrew formula to 2.8. Unfortunately that means the `little-cms2` formula with be stuck with a `version_scheme 1` in it _forever_ unless we can force the downgrade via a 2.9.1 tarball that is equivalent to 2.8.

**Comment by ilovezfs** [comment]
@mm2 Voilà https://github.com/Homebrew/homebrew-core/pull/20718

**Comment by ilovezfs** [comment]
Thanks @mm2 I've now shipped https://github.com/Homebrew/homebrew-core/pull/20718.
