### ISSUE TITLE
Test "Parametric curve on Rec709" fails when building for x86 on x86_64 with gcc -Og

### ISSUE THREAD

**Issue by eroen** [mm2/Little-CMS#143]
This is reproducible on master branch with

```bash
CC="gcc -m32" CFLAGS="-g -Og" sh ./autogen.sh
make && make check
```

The test only fails with -Og, with all of -O2, -Os and -O1 it passes. The tests pass when building for native x86-64 ABI.

This occurs in multiple release versions and with multiple versions of gcc. The attached log is with `gcc version 6.4.0 (Gentoo Hardened 6.4.0 p1.0)` in a fresh checkout of master branch.

See also [Gentoo bug 608524](https://bugs.gentoo.org/608524).

**Comment by eroen** [comment]
[build.log](https://github.com/mm2/Little-CMS/files/1485793/build.log)

**Comment by mm2** [comment]
Thanks for reporting. What is -Og? I was unaware of this, The affected code is just plain math, which is working in all compilers I tested. May be due some assumption  done by the compiler?

**Comment by eroen** [comment]
-Og is one of gcc's optimization presets, along with -O2, -O3, etc. From gcc man page:

       -Og Optimize debugging experience.  -Og enables optimizations that do not interfere with
           debugging. It should be the optimization level of choice for the standard edit-compile-
           debug cycle, offering a reasonable level of optimization while maintaining fast
           compilation and a good debugging experience.

Optimisation settings should generally not affect what results the code produces, but like you say there presumably is an incorrect assumption being made somewhere.

**Comment by mm2** [comment]
Tested with 2.10 and it doesn't fail anymore (gcc fixed it?)
