### ISSUE TITLE
_cmsLinkProfiles is declared twice in src/cmscnvrt.c and src/lcms2_internal.h

### ISSUE THREAD

**Issue by thomas-weber** [mm2/Little-CMS#146]
Subject says it all. The declaration in `lcms2_internal.h` seems to be a copy/paste from the function definition in `src/cmscnvrt.c`; the declaration in `src/cmscnvrt.c` has slightly different names.

This is not problem, but it just seems strange - is there a reason for this replication?

**Comment by mm2** [comment]
fixed in 2.10 rc1
