### ISSUE TITLE
Official release: Sourceforge or Github ?

### ISSUE THREAD

**Issue by nittch** [mm2/Little-CMS#148]
Hello,
  I'm working on integrating last LCMS release.
On Sourceforge there is a 2.9rc3 version ( https://sourceforge.net/projects/lcms/files/lcms/2.9/ ) while in github this is a 2.9b1 ( https://github.com/mm2/Little-CMS/releases -- 2.9rc1).

Github's 2.9b1 seems to be validated by our internal test suite while Sourceforge's 2.9rc3 seems not.

As on https://github.com/mm2/Little-CMS/issues/140 you're saying "Please don't relay on sourceforce for tracking releases.", I'm wondering which one is the official last / stable version?

Thanks for your feedbacks

**Comment by mm2** [comment]
Sorry, forgot to push the tag. Fixed now.
