### ISSUE TITLE
Discuss performance optimizations in context of RawTherapee

### ISSUE THREAD

**Issue by gatoatigrado** [mm2/Little-CMS#149]
Dear all,

I optimized some code for running Lab --> RGB conversions, with the `PrecalculatedXFORM` entry point. Some very basic optimizations yielded a 2.7x speedup in RawTherapee's call site. Currently, it seems that LCMS often jumps to function pointers, which is generally bad for performance because it doesn't work well with the CPU's instruction caching. The current code also often works on single points, which makes vectorization difficult.

The discussion is at https://github.com/Beep6581/RawTherapee/issues/4302 ; if some of the LCMS maintainers wouldn't mind discussing where the optimized code should belong (LCMS, RawTherapee, or some combination), I would appreciate your input. The direct link to the code/diff is https://github.com/gatoatigrado/Little-CMS/pull/1/files.

Thank you very much,
Zora

**Comment by heckflosse** [comment]
I second this.

**Comment by mm2** [comment]
It is a great idea.
I would encourage you to use lcms2 plug-in architecture to pack all your optimisations in a full-transform plug-in, as described in the  "LCMS plugin api" guide.  In this way you can mix c++ and c,  use processor specific optimisations or whatever you wish. The plug-in can even live in the raw therapee space and it is granted to be backwards compatible for incoming lcms versions. 
Regarding to incorporate your changes to base lcms, unfortunately I cannot because  several reasons, like portability, restriction to use  c99 only and so one, but still I think the plug way would fullfil your expectations.

**Comment by mm2** [comment]
Please let me know I you need help on the plug-in, I can provide some samples

**Comment by gatoatigrado** [comment]
Hi Marti, yes some sample links would be appreciated. I found the PDF & it is very nice, but something more "hands on" would also be great. Thank you!

**Comment by mm2** [comment]
Sure,  
You need to implement "ExampleTransform"
The function "CheckTransformPlugin" is a use example.
Hope that helps.


static
void ExampleTransform(struct _cmstransform_struct *CMMcargo,
    const void* InputBuffer,
    void* OutputBuffer,
    cmsUInt32Number PixelsPerLine,
    cmsUInt32Number LineCount,
    const cmsStride* Stride)
{
    cmsUInt32Number i, j;
    const cmsCIELab* input = (const cmsCIELab*)InputBuffer;
    cmsUInt8Number* output = (cmsUInt8Number*)OutputBuffer;

    for (j = 0; j < LineCount; j++)
    {
        for (i = 0; i < PixelsPerLine; i++)
        {
            // read from input, write to output
          }
    }
}

static
cmsBool  TransformFactory(_cmsTransformFn* xformPtr,
    void** UserData,
    _cmsFreeUserDataFn* FreePrivateDataFn,
    cmsPipeline** Lut,
    cmsUInt32Number* InputFormat,
    cmsUInt32Number* OutputFormat,
    cmsUInt32Number* dwFlags)

{
    if (*InputFormat == TYPE_Lab_DBL && *OutputFormat == TYPE_RGB_8)
    {        
        *xformPtr = ExampleTransform;
        return TRUE;
    }

    return FALSE;
}


// The Plug-in entry point
static cmsPluginTransform FullTransformPluginSample = {

    { cmsPluginMagicNumber, 2090, cmsPluginTransformSig, NULL },
    TransformFactory
};

cmsInt32Number CheckTransformPlugin(void)
{
    cmsHTRANSFORM xform;
    cmsCIELab In[] = { { 100, 0, 0}, { 90, 1, 1} };
    cmsUInt8Number Out[2][3];
    
    cmsHPROFILE h, o;
    int i;


    cmsPlugin(&FullTransformPluginSample);
        
    h = cmsCreateLab4Profile(NULL);
    o = cmsCreate_sRGBProfile();
    

    xform = cmsCreateTransform(h, TYPE_Lab_DBL, o, TYPE_RGB_8, INTENT_PERCEPTUAL, 0);
    cmsCloseProfile(h);

    cmsDoTransform(xform, In, Out, 2);

    cmsDeleteTransform(xform);
    
    
    return 1;
}
