### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [mm2/Little-CMS#150]
Hi Little-CMS team,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by mm2** [comment]
Hi, since this is a one-person project, the actual method is ok. Fuzzer sends me private mail when any issue is found, and I have a period of time to fix before making it public. This works very well.

**Comment by Google-Autofuzz** [comment]
Hi,
Just to confirm (since we are a separate effort from OSS-Fuzz, but it sounds like you're describing the OSS-Fuzz notification flow) - for security issues we should mail the contact listed here? https://github.com/google/oss-fuzz/blob/master/projects/lcms/project.yaml

Thanks!
Google Autofuzz Team

**Comment by mm2** [comment]
Yes, that's my private email.

Thanks for your great work!
