### ISSUE TITLE
cmsFLAGS_COPY_ALPHA + Swap-Endian formatter causes bad alpha result

### ISSUE THREAD

**Issue by tannerhelland** [mm2/Little-CMS#159]
Hi Marti,

When the COPY_ALPHA flag is set for a transform, I realize that LittleCMS generally copies alpha data over as-is, without modification.

This is normally desirable behavior, but there is a problem when converting 16-bits-per-channel RGBA data to 8-bits-per-channel RGBA data.  In my case, when using the "COPY_ALPHA" flag with the predefined formatters TYPE_RGBA_16_SE and TYPE_BGRA_8, the transform proceeds without errors, but the resulting 32-bit BGRA data only contains the *least*-significant byte from the original 16-bit alpha channel.

A transform like this is a somewhat common scenario, at least on Windows, as 64-bit PNG data is in RGBA big-endian order, but Windows wants 32-bit BGRA data - hence the TYPE_RGBA_16_SE to TYPE_BGRA_8 formatters.

I can't think of a scenario where a user would want endian-conversion for 16-bit RGB data, but *not* also for its attached 16-bit alpha channel, so maybe this should be revised?

Thank you.

**Comment by mm2** [comment]
Fixed, thank you for reporting!
