### ISSUE TITLE
transicc needs -lm to link

### ISSUE THREAD

**Issue by matt-hayden** [mm2/Little-CMS#160]
On Ubuntu 16.04.4 LTS, the 2.9 release fails with a linking error: the `trunc` function fails to link without `-lm`. I don't think a pull request is appropriate, as you may want to make different autoconf decisions, so a [very humble patch](https://github.com/mm2/Little-CMS/files/1934812/Little-CMS-transicc-linking.patch.txt)

**Comment by mm2** [comment]
Fixed, thanks for reporting!
