### ISSUE TITLE
FormatterPos in cmsalpha.c broken for swapped-endian case

### ISSUE THREAD

**Issue by tannerhelland** [mm2/Little-CMS#162]
Hi Marti,

Thank you for the quick fix to #159.  I believe another fix is needed.

FormatterPos in cmsalpha.c (line 346) is currently broken; it never hits the final test of T_ENDIAN16 (because it will have already exited at previous test `if (b == 2 && !T_FLOAT(frm))`).  And, if it did reach the T_ENDIAN16 test, it would return a wrong index into the table (should return '2' not '3').

This small change seems overkill for a formal pull request, so here is my guess at a fixed function:

```
// Returns the position (x or y) of the formatter in the table of functions
static
int FormatterPos(cmsUInt32Number frm)
{
    cmsUInt32Number  b = T_BYTES(frm);

    if (b == 0 && T_FLOAT(frm))
        return 5; // DBL
#ifndef CMS_NO_HALF_SUPPORT
    if (b == 2 && T_FLOAT(frm))
        return 3; // HLF
#endif
    if (b == 4 && T_FLOAT(frm))
        return 4; // FLT
    if (b == 2 && !T_FLOAT(frm))
		if (T_ENDIAN16(frm))
			return 2; // 16SE
		else
			return 1; // 16
    if (b == 1 && !T_FLOAT(frm))
        return 0; // 8

    return -1; // not recognized
}
```

Thank you!

**Comment by mm2** [comment]
fixed in 2.10 rc1
