### ISSUE TITLE
cmsalpha.c is missing from project files for VC2010 solution

### ISSUE THREAD

**Issue by jstevensonhoare** [mm2/Little-CMS#164]
In the version 2.9 VC2010 solution (lcms2.sln) the projects 'lcms2_DLL' and 'lcms2_static' are missing the 'cmsalpha.c' file.
Without this file an unresolved external '_cmsHandleExtraChannels' is reported by the linker when the 'lcms2_DLL' project is built.
I have not checked the other VC201x versions as I do not have the relevant Visual Studio versions available to me.

**Comment by mm2** [comment]
fixed in 2.10 rc1
