### ISSUE TITLE
VC2010 project builds DLL as file version 2.8.0.0

### ISSUE THREAD

**Issue by jstevensonhoare** [mm2/Little-CMS#165]
In the version 2.9 VC2010 solution (lcms2.sln) the project 'lcms2_DLL' builds the DLL with file version 2.8.0.0 instead of 2.9.0.0.
Looking at the version resource in 'lcms2.rc' it appears that although the ProductVersion and FileVersion attributes have been updated to 2.9.0.0, the FILEVERSION and PRODUCTVERSION attributes are still listed as 2, 8, 0, 0.

**Comment by mm2** [comment]
VC2010 support was supposed to be dropped on 2.9, but the old files are still there. 
Thanks for pointing out.
