### ISSUE TITLE
Bad results using 16 bit planar

### ISSUE THREAD

**Issue by jasonoverland** [mm2/Little-CMS#169]
Hello, I have been replacing our usage of SampleICC with lcms. Internally our pixel buffers are planar (BSQ), so I was using the corresponding input/output formats with lcms. However I was getting strange results for 16 bit images and I finally convinced myself I'm using the library right, but that there is a bug somewhere. We are using 2.9.

I am passing in the number of pixels in cmsDoTransform as instructed. That value gets passed down to PackPlanarWords which uses it directly as 'Stride'. This results in pixels being placed in the wrong location in the buffer. Somewhere along the line this Stride value needs to be multipled by 2 to account for the 2 byte pixels.

So I added a stride *= 2 to the start of PackPlanarWords. After that attempted fix my results were less bad, but still incorrect. 

I gave up and switched to using BIP for our interactions with lcms and all seems to be working.

**Comment by mm2** [comment]
Shoukd be fixed right now
