### ISSUE TITLE
Travis build tests do not show config.log upon failure

### ISSUE THREAD

**Issue by sebras** [mm2/Little-CMS#177]
While my pull request #176 was being [tested](https://travis-ci.org/mm2/Little-CMS/builds/468402065?utm_source=github_status&utm_medium=notification) by travis there were three failures on the mac builds.

On at least [one](https://travis-ci.org/mm2/Little-CMS/jobs/468402067) of these failures I noticed that the command you use to compile is `autoreconf -V && autoreconf --force && ./configure && cat config.log && make && make check`. However that means that `config.log` is not shown if `autoreconf` or `configure` fails, which are the cases when the contents of `config.log` are the most interesting!

I would like for the command to be changed so that `config.log` is shown when there is a failure.

I know very little about Travis myself, but perhaps something along the lines of `(autoreconf -V && autoreconf --force && ./configure && make && make check) || cat config.log` would work? The intention there is to have `cat config.log` run only if any of the prior commands fail. But perhaps the successful error code from cat would interfere with Travis' failure detection?

**Comment by mm2** [comment]
Fixed, thanks for reporting

**Comment by sebras** [comment]
Excellent, thank you! :)
