### ISSUE TITLE
cmsMD5computeID cannot be used to verify the MD5 checksum of an existing profile

### ISSUE THREAD

**Issue by sboukortt** [mm2/Little-CMS#181]
In [PIK](https://github.com/google/pik), we try to detect MD5 mismatches using `cmsMD5computeID` and comparing the output to the embedded profile ID:

https://github.com/google/pik/blob/16268ef512a65b541c7b5e485468a7ed33bc13d8/pik/color_management.cc#L139-L160

But it turns out not to be a reliable approach because when re-serializing the profile in memory to compute its checksum, LCMS 2 discards the original “creator” and “preferred CMM” tags and replaces them with its own.

Here is [an example profile](https://github.com/mm2/Little-CMS/files/3085805/example.zip) on which LCMS 2 exhibits this behavior. It was created using DisplayCAL’s “Synthetic ICC” utility. The archive also includes the output of `cmsSaveProfileToMem` from within `cmsMD5computeID`.

**Comment by mm2** [comment]
You are right. There is no way to check MD5 of profiles from other vendors. Reason is, the tags and functionality of the profile can be serialized as  files in many different ways, so you can have two quite different files holding same color rendition. Then lcms2 offers ways to read, use and create icc profiles, but not a way to check conformance or even suitability of those profiles. Having said that, your best option is just to load the intended profile in a memory block, force some fields to default values, as required by icc spec, and then compute MD5 as a raw binary block.

**Comment by sboukortt** [comment]
That does sound like a sensible approach, thank you for the suggestion. Would it sound reasonable to expose the MD5 implementation in LCMS 2 to that effect? That would avoid multiplying dependencies for users who wish to do this.

Thanks!

**Comment by mm2** [comment]
Sure! It is now in the GIT
You can use github's latest until a new release is done, I would like to update the manual before that.
