### ISSUE TITLE
overflow at WriteMatrix() in cmstypes.c

### ISSUE THREAD

**Issue by wenj1104** [mm2/Little-CMS#183]
https://github.com/mm2/Little-CMS/blob/65c63bf549d78253c14b30b3d62cb668bbbe612c/src/cmstypes.c#L2551

If the actual length of the double array is less than 9, then the arrry access will be out of bounds.

**Comment by mm2** [comment]
Fixed by 9632a058a0c617a6461a1c32bc437fef87b3de9c
Many thanks for reporting
