### ISSUE TITLE
Pixel type defines(PT_*,TYPE_*) are too simple to avoid conflict

### ISSUE THREAD

**Issue by nikq** [mm2/Little-CMS#185]
Some defined macros are too simple name and cannot avoid conflicting from already existed code base.
I thought using prefix "cms" as same as other macros will improve this problem.

e.g.
PT_GRAY > cmsPT_GRAY
TYPE_GRAY_8 > cmsTYPE_GRAY_8

Thanks.

**Comment by mm2** [comment]
Unfortunately changing this would break backwards compatibility. I suggest either to #undef the offending macro or, #define TYPE_RGB_8, which would prevent lcms2.h to define all those symbols (see lcms2.h, line 746)
