### ISSUE TITLE
Failure to create a transform to “Apple Wide Color Sharing Profile”

### ISSUE THREAD

**Issue by sboukortt** [mm2/Little-CMS#188]
Hi,

Apparently, iPhones can now create images with a custom-made ICC profile:

> We're also an industry in transition right now, so some photo services don't understand wide color, but most of them at least are smart enough to render it as sRGB. For mixed sharing scenarios, like say sending a photo via Messages or Mail, you don't know where it's going. It might be going to multiple devices. Some of them might support wide color. Some might not.
>
> So for this situation, we have added a new service called Apple Wide Color Sharing Profile. Your content can be manipulated in a way that we generate a content specific table-based ICC profile that's specific to that particular JPEG. And what's nice about it is if it's rendered by someone who doesn't know about wide color, the part that's in the sRGB gamut renders absolutely correctly. The extra information is carried in the extra ICC profile information in a way that they can recover the wide color information with minimal quality loss.

— [Advances in iOS Photography](https://asciiwwdc.com/2016/sessions/501)

However, while using such profiles as a **source** for transforms appears to work, LCMS2 fails to create a transform **to** them, as illustrated by the following code:

~~~c
/*
 * Copyright 2019 Google LLC.
 * SPDX-License-Identifier: Apache-2.0
 */

#include <lcms2.h>
#include <stdio.h>

int main(void) {
  cmsHPROFILE srgb = cmsCreate_sRGBProfile();
  cmsHPROFILE wide = cmsOpenProfileFromFile("Apple-Wide.icc", "r");
  cmsHTRANSFORM transform = cmsCreateTransform(
      srgb, TYPE_RGB_FLT, wide, TYPE_RGB_FLT, cmsGetHeaderRenderingIntent(wide),
      cmsFLAGS_HIGHRESPRECALC);
  printf("srgb = %p\n", srgb);
  printf("wide = %p\n", wide);
  printf("transform = %p\n", transform);
  if (transform) {
    cmsDeleteTransform(transform);
  }
  cmsCloseProfile(wide);
  cmsCloseProfile(srgb);
  return 0;
}
~~~

Which outputs:

~~~console
srgb = 0x5585a1a14400
wide = 0x5585a1a12340
transform = (nil)
~~~

The chain of functions that fails seems to be: `cmsCreateTransform` → `cmsCreateTransformTHR` → `cmsCreateMultiprofileTransformTHR` → `cmsCreateExtendedTransform` → `_cmsLinkProfiles` → `DefaultICCintents` → `_cmsReadOutputLUT` → `BuildRGBOutputMatrixShaper` → `ReadICCMatrixRGB2XYZ` → `cmsReadTag` (reading `cmsSig{Red,Green,Blue}ColorantTag` fails).

And indeed, the profile does not seem to include primaries, only a look-up table. I am not sure that I can attach the profile here (“Copyright Apple Inc.”), but here is the output of `cd-iccdump`:

~~~console
icc:
Header:
  Size          = 30240 bytes
  Version       = 4.0
  Profile Kind  = input-device
  Colorspace    = rgb
  Conn. Space   = xyz
  Date, Time    = 2016-01-01, 00:00:00
  Flags         = Not embedded profile, Use anywhere
  Dev. Attrbts  = reflective, glossy
  Rndrng Intnt  = perceptual
  Creator       = appl
  Profile ID    = e6e9f2ad410a663dd5b3daa1e2075bd5
tag 00:
  sig   'desc' [0x64657363]
  size  192
  type  'desc' [0x64657363]
Text:
  **_**:        Apple Wide Color Sharing Profile [132 bytes]

tag 01:
  sig   'cprt' [0x63707274]
  size  35
  type  'text' [0x74657874]
Text:
  **_**:        Copyright Apple Inc., 2016 [108 bytes]

tag 02:
  sig   'wtpt' [0x77747074]
  size  20
  type  'XYZ ' [0x58595a20]
XYZ:
  X:0.964203 Y:1.000000 Z:0.825104

tag 03:
  sig   'A2B2' [0x41324232]
  size  29772
  type  'mAB ' [0x6d414220]

tag 04:
  sig   'chad' [0x63686164]
  size  44
  type  'sf32' [0x73663332]

tag 05:
  sig   'aapy' [0x61617079]
  size  14
  type  'data' [0x64617461]

tag 06:
  sig   'A2B0' [0x41324230]
  link  'A2B2' [0x41324232]
tag 07:
  sig   'A2B1' [0x41324231]
  link  'A2B0' [0x41324230]
~~~

Is it something that looks reasonably easy to fix?

**Comment by sboukortt** [comment]
Somewhat unrelatedly, it seems a bit surprising that `cmsDeleteTransform` fails when given a null transform when `cmsCloseProfile` accepts null pointers without issue.

**Comment by mm2** [comment]
Hi, this profile is one of those rares which only can operate in input direction (the A2BX tags are there, but B2AX are missing).

With primaries, the CMM could try an approximation, but unfortunately the A2B tags are not invertible.

So lcms is doing the right thing: you can open the profile but you only can use it as input.

Regarding the NULL check, I'm adding the change.

Thanks!
