### ISSUE TITLE
Plausible fix of OSS-fuzz 12829

### ISSUE THREAD

**Issue by gaoxiang9430** [mm2/Little-CMS#189]
Hi, I noticed that OSS-fuzz detects a [stack-overflow vulnerability](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12829) in LCMS, which is reported on May 2, 2019, but it seems that the bug has not been fixed yet. In the latest version, I found the bug can still be reproduced. Here are some automatically generated patches that can prevent the stack-overflow, which may completely or partially fix the bug. That will be great if you can let us know whether the patches are correct or whether those patches are helpful for developers to fix the bug. Your feedback is highly appreciated.
```
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if ((SINCLUDE < 15)) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if ((SINCLUDE <= 12)) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (it8->sy != SINCLUDE))) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (SINCLUDE < 15))) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (SINCLUDE <= 3))) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (SINCLUDE <= 4))) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (it8->sy < 9))) {
--- a/src/cmscgats.c
+++ b/src/cmscgats.c
905c905
<     if (it8 -> sy == SINCLUDE) {
---
>     if (((it8->sy == SINCLUDE) && (it8->sy < it8->sy))) {

```

**Comment by mm2** [comment]
Thnaks for reporting. If you take a look [on the link you provided to the issue](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12829), you can see [a comment from me](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12829#c3) that this bug is not such. 
Fuzzer assumes an infinite loop after recursion 18, whilst lcms allows up to 20 nested includes. That is, fuzzer assumption is wrong and there is **NO BUG**, and **NO VULNERABILITY**.
