### ISSUE TITLE
 Contact us about VC2019 support.

### ISSUE THREAD

**Issue by cepiloth** [mm2/Little-CMS#195]
Hello.
I Fork the LITTLE-CMS project. And we added VC 2019 project configuration.
I want to contribute to this project.

I want to know how I can participate.
my repository address is https://github.com/cepiloth/Little-CMS.

thank you.

**Comment by ValZapod** [comment]
@cepiloth Just give pull request, it is not code, so no license or copyright issues.

**Comment by cepiloth** [comment]
ok thank you.
