### ISSUE TITLE
ImageMagick compiled with LCMS2 and GSLIB support coredumps while convert pdf to png

### ISSUE THREAD

**Issue by VVD** [mm2/Little-CMS#207]
All information include gdb's backtrace are here ImageMagick/ImageMagick#1908.
LCMS 2.9, compiled with JPEGICC and TIFFICC options.

**Comment by mm2** [comment]
The lcms2 default log error handler does nothing. Seeing the coredump seems the lcms2 caller has set a custom log error handler  that raises a signal. Lcms2 founds a bad profile, logs the error and then the custom handler messes out things. Obvioulsly if you removes all lcm2 library the log error handler is not called  at all, but I think it would make more sense to fix this misbehaviour in the  caller side: either avoid setting log error handler or, better, fix the code of the function.

**Comment by VVD** [comment]
Issue at FreeBSD's bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245782

**Comment by mm2** [comment]
After reviewing the code, this is not a lcms2 bug. It seems the function is called with wrong arguments or something like that.

**Comment by VVD** [comment]
Is this bug must be addressed to ghostscript?

**Comment by mm2** [comment]
Probably, there is nothing to fix in the original library. I suspect they changed parameters whilst keeping the same (exported) function name. But this is only my guessing. Good luck.

**Comment by VVD** [comment]
https://bugs.ghostscript.com/show_bug.cgi?id=702349

**Comment by VVD** [comment]
It fixed in ghostscript: http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=f210e4c009f7
