### ISSUE TITLE
Is there a way to query the parametric constants for a tone curve?

### ISSUE THREAD

**Issue by DominikDeak** [mm2/Little-CMS#218]
We can query the tone curve type using the `cmsGetToneCurveParametricType` function. Is there an equivalent way to access the parametric constants for a `cmsToneCurve` struct? If not, how practical is implementing such a feature in the API?

**Comment by mm2** [comment]
Actually there is no function to do that, but I think it would be quite easy, something like:

cmsFloat64Number*  cmsGetToneCurveParams(const cmsToneCurve* t)
{
    _cmsAssert(t != NULL);

    if (t -> nSegments != 1) return NULL;
    return t ->Segments[0].Params;
}

I will add this to the development sources, thanks for the idea!

**Comment by mm2** [comment]
Included in 2.11

**Comment by DominikDeak** [comment]
Thank you!
