### ISSUE TITLE
Crash when calling cmsMD5computeID on a profile with malformed 'mluc' for tag 'cprt'

### ISSUE THREAD

**Issue by DominikDeak** [mm2/Little-CMS#220]
When I create a RGB profile, set the copyright data with an empty string, then call `cmsMD5computeID` on said profile, the program crashes.

### Steps to Reproduce

1. Create a context, and attach an error handler for debugging purposes.
2. Create a RGB profile.
3. Set the copyright MLU with an empty ASCII string: `""`. This will log the following error:
    `12 Malformed struct in type 'mluc' for tag 'cprt'`
4. Call `cmsMD5computeID` on the profile. This will crash the application.
5. To prevent the crash, either comment out the`cmsMD5computeID` function call, or use a non-empty MLU string `" "` for the copyright tag.

See code snippets below as a guide.

### Sample Code

Error handler:

```cpp
static void ErrorHandler( cmsContext context, cmsUInt32Number errorCode, const char* message )
   {
   printf( "%u %s\n", errorCode, message );
   };
```
Code to reproduce the bug:

```cpp
cmsContext context = cmsCreateContext( NULL, NULL );
assert( context );
cmsSetLogErrorHandlerTHR( context, ErrorHandler );

cmsCIExyY white = { 0.31271, 0.32902, 1.0 };
cmsCIExyYTRIPLE primaries =
   {
  .Red   = { 0.640, 0.330, 1.0 },
  .Green = { 0.300, 0.600, 1.0 },
  .Blue  = { 0.150, 0.060, 1.0 }
   };

cmsFloat64Number parameters[ 10 ] = { 2.6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
cmsToneCurve* toneCurve = cmsBuildParametricToneCurve( context, 1, parameters );
assert( toneCurve );
cmsToneCurve* toneCurves[ 3 ] = { toneCurve, toneCurve, toneCurve };

cmsHPROFILE profile = cmsCreateRGBProfileTHR( context, &white, &primaries, toneCurves );
assert( profile );

cmsFreeToneCurve( toneCurve );

// Set an empty copyright tag. This should log an error.
cmsMLU* mlu = cmsMLUalloc( context, 1 );
assert( mlu );
cmsMLUsetASCII( mlu, "en", "AU", "" );
cmsWriteTag( profile, cmsSigCopyrightTag, mlu );
cmsMLUfree( mlu );

// This will cause a crash after setting an empty copyright tag.
cmsMD5computeID( profile );

// Cleanup
cmsCloseProfile( profile );
cmsDeleteContext( context );
```
### Stack Trace

```
#0 0x000000010220f738 in SaveTags ()
#1 0x000000010220f3cc in cmsSaveProfileToIOhandler ()
#2 0x000000010220fba8 in cmsSaveProfileToMem ()
#3 0x00000001022188f3 in cmsMD5computeID ()
#4 0x0000000100bd9e66 in SkalaCore::Test::LCMSCrash() 
```

### Other Info

OS: macOS Catalina
Compiler: XCode 11.5 (11E608c)
LCMS Library: v2.10, obtained from [Conan Center](https://github.com/conan-io/conan-center-index)

**Comment by mm2** [comment]
It is now fixed by a483dfa260e86fc1de7c917f2e2575db9c27d9a6
Thanks a lot, the sample code has been extremly useful in finding & fixing the issue. It is now on testbed as well.
