### ISSUE TITLE
Colorimetric gamut clipping for out-of-gamut colors?

### ISSUE THREAD

**Issue by haasn** [mm2/Little-CMS#221]
I noticed that when creating a `cmsHTRANSFORM` mapping from a wide gamut color space (e.g. BT.2020) to a narrow gamut color space (e.g. BT.709), out-of-gamut colors simply end up clipped per-channel:

```c
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>

#include <lcms2.h>

int main()
{
    cmsCIExyY wp_d65 = { 0.31271, 0.32902, 1.0 };
    cmsCIExyYTRIPLE prim_bt2020 = {
        .Red   = {0.708, 0.292, 1.0},
        .Green = {0.170, 0.797, 1.0},
        .Blue  = {0.131, 0.046, 1.0},
    };

    cmsCIExyYTRIPLE prim_bt709 = {
        .Red   = {0.640, 0.330, 1.0},
        .Green = {0.300, 0.600, 1.0},
        .Blue  = {0.150, 0.060, 1.0},
    };

    cmsToneCurve *curves[3];
    curves[0] = curves[1] = curves[2] = cmsBuildGamma(NULL, 2.2);

    cmsHPROFILE bt2020, bt709;
    bt2020 = cmsCreateRGBProfile(&wp_d65, &prim_bt2020, curves);
    bt709 = cmsCreateRGBProfile(&wp_d65, &prim_bt709, curves);
    cmsFreeToneCurve(curves[0]);

    cmsHTRANSFORM trafo = cmsCreateTransform(bt2020, TYPE_RGB_16,
                                             bt709, TYPE_RGB_16,
                                             INTENT_RELATIVE_COLORIMETRIC,
                                             cmsFLAGS_NOCACHE | cmsFLAGS_NOOPTIMIZE);

    uint16_t src[3] = {31529, 7826, 7046};
    uint16_t dst[3];

    cmsDoTransform(trafo, src, dst, 1);
    printf("original: %"PRIu16" %"PRIu16" %"PRIu16"\n", src[0], src[1], src[2]);
    printf("transformed: %"PRIu16" %"PRIu16" %"PRIu16"\n", dst[0], dst[1], dst[2]);

    cmsDeleteTransform(trafo);
    cmsCloseProfile(bt2020);
    cmsCloseProfile(bt709);
}
```

```
$ gcc lcms.c -o lcms -llcms2 && ./lcms
original: 31529 7826 7046
transformed: 39374 0 5149
```

We can see clearly that this is a naive per-component clip, because performing the BT.2020->BT.709 conversion manually, I get `39374 NaN 5149` (where `NaN` is the result of applying the gamma 2.2 curve to the negative value `-944`). Simply clamping the out-of-range component like this significantly alters the subjective appearance of the color, in a way that is surely not done to minimize dE loss.

Computing the dE between the original (Lab 29.2328 62.6251 38.7994) and the transformed (Lab 31.7156 55.2905 40.6235) I get a dE 2000 of 3.842154. Manually desaturating the color (by reducing the LCh chromaticity until the color is within gamut - similar to what `cmsDesaturateLab` is doing) instead gives me Lab 29.2328 52.5482 32.5563, which differs by a dE 2000 of only 2.928193. We can see that in this case, LCh desaturation gives us an objectively closer result to the original color.

I was under the impression that LittleCMS will perform exactly this sort of colorimetric gamut clamping out of the box, but apparently this is not the case. Is there any way to get LittleCMS to do this for me?

**Comment by haasn** [comment]
Oh, it's worth pointing out that removing `cmsFLAGS_NOOPTIMIZE` actually affects the output (I thought it'd just affect performance?), giving me `39371 0 5023` (Lab: 31.7097 55.2785 40.8807) instead. This isn't a huge change though, just a minor deviation.

**Comment by mm2** [comment]
LittleCMS definitively can do gamut mapping. You got this behaviour because you are using the simplified built-in RGB matrix-shaper. Those profiles are basically intended for input. 
If you want to see gamut mapping in action, use [sRGB v4 Preference as output , for example](http://color.org/srgbprofiles.xalter#v4pref) and perceptual intent. You will see a huge difference. 

Anyway, this is the ICC model. The "smartness" of gamut mapping relies on the profile, not on the CMM.

**Comment by haasn** [comment]
Ah, I understand. I guess it comes down to how well-made the profile is, at the end of the day, and whether or not it contains a good "perceptual mapping". That's unfortunate, especially when using relative colorimetric intent (which still produces badly-clipped colors even on that sRGB v4 profile), but I guess it's the way things are.

**Comment by mm2** [comment]
Actually this is a very complex topic. Since the destination gamut cannot reproduce the desired color, all neighboring  have to be moved to preserve smothness and gradients. This is perceptual intent and many times it involves *art*. Just clipping is a gamut mapping too. 

A good book on this: Color Gamut Mapping by Ján Morovič
