### ISSUE TITLE
Performance impact by passing CAM02COLOR as value.

### ISSUE THREAD

**Issue by ya1gaurav** [mm2/Little-CMS#228]
There are so many calls which passes CAM02COLOR (264 bytes) as value. It will degrade ther performance by making copies while passing in arguement and while returning.
Pointers can be used instead.
 XYZtoCAT02, ChromaticAdaptation, CAT02toHPE, NonlinearCompression, ComputeCorrelates, InverseCorrelates, InverseNonlinearity, HPEtoCAT02, InverseChromaticAdaptation, CAT02toXYZ

**Comment by ya1gaurav** [comment]
Such a PR would be acceptable?

**Comment by mm2** [comment]
Thanks, this is on purpose. CAM02 is a complex math model NOT USED on color conversions. It is there for specialized clients, like color profilers. In this case, speed is not important but code clarity is, and this implementation allows user to pinpoint values in debug mode.

**Comment by mm2** [comment]
After further investigation, I found the compiler does a great job optimizing those calls (please note they are static)
So probably using a pointer would not result in  a great speed improvement at all.
