### ISSUE TITLE
inconsistency between Type_LUT8_Write and Type_LUT16_Write 

### ISSUE THREAD

**Issue by etrinh** [mm2/Little-CMS#229]
I noticed an inconsistency which creates an issue while trying to save a gamut table (lut8) in v2.1 format. It worked with lcms v2.7 (didn't try newer).
It appeared that the `Type_LUT8_Write` function add a test at cmstypes.c:1916
`if (n != 9) return FALSE;`
where n is NewLUT->InputChannels * NewLUT->OutputChannels
When input and/or output != 3, then writing the profile fails. I 'guess' matrices are unused for these spaces...
Also, this test is not present in `Type_LUT16_Write`

**Comment by etrinh** [comment]
Issue came from `fix array bounds on writing matrices` commit
Issue was fixed for Type_LUT16_Write in `Fix Lut16 matrix` commit

**Comment by mm2** [comment]
Fixed in 29b0d7953af3a49ed524042e4622a842e38e3329
Thanks for reporting
