### ISSUE TITLE
Build Integration of fast_float

### ISSUE THREAD

**Issue by butcherg** [mm2/Little-CMS#231]
Trying to incorporate fast_float into my lcms2 support.  I extracted and installed the relevant build file modifications from pull request #230, and the plugin built as liblcms2_fast_float.a.  Well and good, but my attempt to link that into my application produced the following error:

```
/usr/bin/ld: /home/glenn/ImageStuff/rawproc-build-support/Little-CMS/build-fast/plugins/fast_float/src/.libs/liblcms2_fast_float.a(fast_float_sup.o): in function `Floating_Point_Transforms_Dispatcher':
/home/glenn/ImageStuff/rawproc-build-support/Little-CMS/build-fast/plugins/fast_float/src/../../../../plugins/fast_float/src/fast_float_sup.c:59: undefined reference to `Optimize16BitRGBTransform'
```
The caller and the 'undefined reference' are both in fast_float_sup.o, included in liblcms2_fast_float.a.  I'm including the liblcms2.a and liblcms2_fast_float.a in that order in my link command.

Maybe a few words in the plugin doc about how to do this would help... thanks.

**Comment by mm2** [comment]
Thanks for reporting, 
Should be fixed on b78a296b3e28a2e6b1998caebeb370c5b511dd3a

**Comment by butcherg** [comment]
Still no joy, same error as my first post. 

I cloned the master branch, applied a patch I created to make the configure.ac and Makefile.am changes, then autoconf, automake, and make, and that created the liblcms2_fast_float.a.  I linked it into my raw processor application, that worked, but when I added the cmsPlugin(cmsFastFloatExtensions()); to my initialization, the same link error as reported before occurred:

```
/usr/bin/ld: /home/glenn/ImageStuff/rawproc10/build-support/Little-CMS_fastfloat/build-linux/plugins/fast_float/src/.libs/liblcms2_fast_float.a(fast_float_sup.o): in function `Floating_Point_Transforms_Dispatcher':
/home/glenn/ImageStuff/rawproc10/build-support/Little-CMS_fastfloat/build-linux/plugins/fast_float/src/../../../../plugins/fast_float/src/fast_float_sup.c:60: undefined reference to `Optimize16BitRGBTransform'
```
I may and well be doing something wrong but I can't see how a function in a fast_float .o can't find another function in the same .o file...

Thanks...

**Comment by mm2** [comment]
Make sure the file fast_16_tethra.c is included in your project.
It is where this function is defined. I checked it, even mixing C/C++ and it is working for me.

**Comment by butcherg** [comment]
The caller, Floating_Point_Transforms_Dispatcher, and the callee, Optimize16BitRGBTransform, are both in fast_float_sup.c  I did this:

```
nm -C liblcms_fast_float.a
```

to list the library contents, and I found this:

```
fast_float_sup.o:
00000000000001d0 T cmsFastFloatExtensions
0000000000000000 t Floating_Point_Transforms_Dispatcher
                 U Formatter_15Bit_Factory
                 U _GLOBAL_OFFSET_TABLE_
                 U Optimize16BitRGBTransform
                 U Optimize8BitRGBTransform
                 U Optimize8ByJoiningCurves
                 U Optimize8MatrixShaper
                 U Optimize8MatrixShaperSSE
                 U OptimizeCLUTCMYKTransform
                 U OptimizeCLUTRGBTransform
                 U OptimizeFloatByJoiningCurves
                 U OptimizeFloatMatrixShaper
                 U OptimizeMatrixShaper15
0000000000000000 d PluginFastFloat
0000000000000000 d PluginList
```

**Comment by butcherg** [comment]
Ah, I can't read nm output, it seems.  Floating_Point_Transforms_Dispatcher is in fast_float_sup, and it's calling Optimize16BitRGBTransform which is in fast_16_tethra.c That's what's missing from the Makefile.am in plugins/fast_float/src/.

**Comment by mm2** [comment]
Oh, I see. Sorry, the .am file was there just as a work in progress, there is not yet a building system for the plugin.  Yep, only a short comment on manual sayingn you have to add sources by hand... confusing. I will delete it until complete.

**Comment by butcherg** [comment]
...and now my application links.  And OMG is it fast!  I recently refactored my display pipeline, and in doing so had to move from an 8-bit color transform to floating point.  It is now speedy-quick!

I'll  just patch my clone for the time being; I'd offer to make a pull request for the complete thing, but I'm trying to put a bow on version 1.0 of my raw processor: https://github.com/butcherg/rawproc.  It's used LittleCMS for a couple of releases now, and it works really well with the toolchain concept.  Thanks for what you do!

**Comment by mm2** [comment]
Excellent news! Thanks for let me know.
