### ISSUE TITLE
RGB to cmyk 

### ISSUE THREAD

**Issue by 947942434** [mm2/Little-CMS#233]
The same jpg.icc (japan color 2001 coated) file converts the color difference
RGB (235,235,235) Photoshop CMYK (9,7,7,0) lcms2 cmyk (9,8,7,0)
RGB (234,22,21) Photoshop CMYK (8,96,99,0) lcms2 cmyk (7,97,97,0)

Is there any way I can reduce the color difference between lcms and Photoshop?

Whether pantone icc will be mixed later

**Comment by 947942434** [comment]
C:\Windows\System32\spool\drivers\color
tif.icc is error
jpg.icc is japan color 2001 coated

**Comment by mm2** [comment]
Please check the rendering intent. You should use same rendering intent in photoshop and in lcms to compare numbers.
This has been tested many times, lcms match pretty well photoshop numbers.

**Comment by 947942434** [comment]
src 
![123](https://user-images.githubusercontent.com/34594744/97826091-9bba9f00-1cfb-11eb-8c3c-aeb2719bea9f.jpg)
dst
![22](https://user-images.githubusercontent.com/34594744/97826107-a8d78e00-1cfb-11eb-9ae6-1da0937b637f.jpg)

Can I give an rgb to cmyk test routine? What's wrong with my current test?

My test program:
cmsHTRANSFORM xform = cmsCreateTransform(sRGB.icc,TYPE_RGB_8, cmyk.icc, TYPE_CMYK_8, INTENT_PERCEPTUAL, 0);
cmsDoTransform(xform, in->buf, out->buf, wh);

Whether it needs to be as follows?
rgb => lab => cmyk ?

**Comment by 947942434** [comment]
![55](https://user-images.githubusercontent.com/34594744/97852915-56fe2a80-1d32-11eb-8335-cbfc3bc0c175.jpg)
Print out the picture and find that the background color difference is particularly large! Others also have color difference!  

Thank you.

**Comment by mm2** [comment]
japan2001coated.icc is a 8 bits profile,  you have to expect poor resolution from this profile.  Specially on gamut boundaries.

Just to prove what I'm saying, I tried ColorSync. 

In you sample of sRGB=(234, 22, 21)  / perceptual which, by the way is an out of gamut color, you report:

Photoshop = (8, 96, 99, 0) 

I got using ColorSync utility CMYK =( 25, 242, 245, 0)  dividing by 255 and multiplying per 100 I got (9.8, 94.9, 96.0) after rounding:  

ColorSync = (10, 95, 96, 0) 

This is way off the value you report from photoshop! Which one we have to trust? Adobe or Apple?

With transicc: 
marti@macs-Mac-mini Profiles % transicc -i "sRGB_Color_Space_Profile.icm" -o JapanColor2001Coated.icc -t0 
LittleCMS ColorSpace conversion calculator - 4.3 [LittleCMS 2.10]

Enter values, 'q' to quit
R? 234
G? 22
B? 21

C=7.4205 M=96.7086 Y=98.5733 K=0.0000 

LittleCMS=(7, 97, 99), which seems closer that ColorSync.

Anyway, if you want to check numbers make sure to de-activate all optimisations, use cmsFLAGS_NOOPTIMIZE when creating transforms. Other profiles, in particular 16 bits ones, would match better PhotoShop.
