### ISSUE TITLE
[Question] Do you have any plan to support "Color Exchange Format (CxF)"?

### ISSUE THREAD

**Issue by diuming** [mm2/Little-CMS#235]
Do you have any plan to support "Color Exchange Format (CxF)"?
thanks

**Comment by mm2** [comment]
> Do you have any plan to support "Color Exchange Format (CxF)”?
> 
Not really. Please note lcms is a CMM, it does not need measurements. CxF, now an ISO standard, was largely under X-Rite control, so I never tried to implement it because it was proprietary at the time.
Anyway I guess any capable XML reader would do the job.

Regards
Marti
