### ISSUE TITLE
Should cmsOpenProfileFromMem validate the data passed in?

### ISSUE THREAD

**Issue by tsdgeos** [mm2/Little-CMS#239]
While fuzzing poppler I have found that if we feed "relately good but crap" data to cmsOpenProfileFromMem, then when asking for `cmsGetColorSpace` i get returned 2233470993 which isn't a valid `cmsColorSpaceSignature`

I had a look at the code and was wondering if it makes sense for `_cmsReadHeader` to return false if the things read from the header don't correctly map to any of the valid values.

**Comment by mm2** [comment]
Hello, 

Sorry about the delay,  

It could be a good idea if people would keep ICC registry up to date, which unfortunately doesn’t happen. I found many vendors using their own signatures for they own data. This makes profiles incompatible. Specially on V2 profiles.

lcms tries to be very permissive until some operation involving the specific data is requested. I.e, this profile probably would be open and read, but when you try to combine in a color transform would fail.
Is that the best way to deal with crappy profiles? I don’t know. The other way, to be very strict, would make many, many (trust me!) profiles unsuitable. Programs like Photoshop allows such wrong profiles, which doesn’t help. The current approach is to allow user code to do all validations in the app side. Lcms complains only when data is needed and it is corruped or not handled.
 
> While fuzzing poppler I have found that if we feed "relately good but crap" data to cmsOpenProfileFromMem, then when asking for cmsGetColorSpace i get returned 2233470993 which isn't a valid cmsColorSpaceSignature
> 
> I had a look at the code and was wondering if it makes sense for _cmsReadHeader to return false if the things read from the header don't correctly map to any of the valid values.
> 
> 
>

**Comment by tsdgeos** [comment]
> The current approach is to allow user code to do all validations in the app side. 

But we can't because you're giving us a `cmsColorSpaceSignature` that can not legally hold 2233470993 (the compiler could make things explode in flames, that's what undefined behavior means).

If you don't want to validate what `_cmsReadHeader` reads and what `cmsGetColorSpace` returns, which is a fair decision, then in my opinion `cmsGetColorSpace` should just return a `cmsUInt32Number` and document that the "known" values are the values enumerated at `cmsColorSpaceSignature` but that there could be more".

**Comment by mm2** [comment]
I may be wrong, but I think in C99 enums are always using unsigned int and you can safely do an (unsigned int) cast. This is not true on C++, but lcms is written in C99.

Maybe the solution would be to provide an additional function to validate header, something like “cmsBool cmsValidateHeader(..)”

**Comment by tsdgeos** [comment]
meh, you're right, this is a C vs C++ difference
```
$ clang -std=c17 -g3 -fsanitize=undefined main.c && ./a.out 
B

$ clang++ -std=c++20 -g3 -fsanitize=undefined main.c && ./a.out 
main.c:59:13: runtime error: load of value 2233470993, which is not a valid value for type 'cmsColorSpaceSignature'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior main.c:59:13 in 
B
```

oh well, i guess i can live with that UndefinedBehaviorSanitizer warning while it's just a warning, if the compiler starts crashing or doing weird stuff in the future i'll try to figure out how to solve this.

Sorry for taking your time :)
