### ISSUE TITLE
sf.net 2.12 download tarball is broken

### ISSUE THREAD

**Issue by brechtsanders** [mm2/Little-CMS#242]
lcms2-2.12.tar.gz from SourceForge (https://sourceforge.net/projects/lcms/files/lcms/2.12/) is broken.
`configure` fails because `install-sh` is missing (`configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."`), and because `configure.ac` is missing too the `autgen.sh` script also fails.
The GitHub download of the file with the same name is fine though.

**Comment by mm2** [comment]
I have double checked the tarball against Mac, Windows and Debian and its fine to me.
Could you tell me the exact steps you have taken?

**Comment by brechtsanders** [comment]
I downloaded the tarball from http://downloads.sourceforge.net/project/lcms/lcms/2.12/lcms2-2.12.tar.gz where at least the files `install-sh` and `configure.ac` were missing.
Then I downloaded it from https://github.com/mm2/Little-CMS/releases/download/lcms2.12/lcms2-2.12.tar.gz and there were no issues.

**Comment by brechtsanders** [comment]
I tried it again now and now I can't reproduce the issue.
Must have been a sf.net download/package issue...

**Comment by mm2** [comment]
Probably a sf issue. Thanks for reporting anywayOn 7 Feb 2021 12:08, Brecht Sanders <notifications@github.com> wrote:
Closed #242.
