### ISSUE TITLE
Please remove all 'register' keywords - they provide no benefit

### ISSUE THREAD

**Issue by yurivict** [mm2/Little-CMS#243]
clang complains:
```
usr/local/include/lcms2.h:158:23: note: expanded from macro 'CMSREGISTER'
#  define CMSREGISTER register
                      ^
/usr/local/include/lcms2.h:1263:44: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
                                           CMSREGISTER void * Cargo);
                                           ^~~~~~~~~~~~
```

**Comment by mm2** [comment]
This library is written in and requires c99. Having said this, there is a toggle to remove the register storage class when you are  using c++, this is explained in the tutorial "Introduction - the register keyword"

**Comment by yurivict** [comment]
c99 also doesn't require the ```reqister``` keyword.

**Comment by mm2** [comment]
From ISO/IEC 9899:TC2 "6.7.1 Storage-class specifiers""4 A declaration of an identifier for an object with storage-class specifier registersuggests that access to the object be as fast as possible. The extent to which suchsuggestions are effective is implementation-defined"'register' is part of c99 language and littlecms is written using c99 language. Additionally, you can compile it with a c++ compiler, but you need to configure some settings to do so.On 9 Feb 2021 22:34, "yuri@FreeBSD" <notifications@github.com> wrote:
c99 also doesn't require the reqister keyword.

**Comment by arichardson** [comment]
On any compiler written in this century `register` makes absolutely no difference to the generated code (except possibly at -O0, but if you use -O0 you get slow code anyway). The only time it makes sense to use this keyword is for direct access to registers asm variable, but that is a very niche use-case.
