### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by therahedwig** [mm2/Little-CMS#245]
https://github.com/mm2/Little-CMS/blob/ab541149609b20da770f427e9ca72b40230665a4/src/cmsgamma.c#L645

The documentation says 8 has parameters 'gamma, a, b, c, d, e', while in the formula gamma is unused, and in the code, it treats 0 as 'a'.

**Comment by mm2** [comment]
Thanks! 
It is now fixed in the .docx file, you will see the changes on next release, when I publish the PDF
