### ISSUE TITLE
"segmentation fault" in function "cmsDoTransform"

### ISSUE THREAD

**Issue by keerm-code** [mm2/Little-CMS#252]
hey MM
I  copy the demo”rgbtocmyk ”(which is in tutorial) to change a rgb data to cmyk
my iccs are from qt icc(linux 5.12.10).
and I use the func cmsCreateTransform to create a transform.
It works.
Then I use cmsDoTransform func .
I pass the transform I created ,a rgb data(type uchar[3])and a cmyk data(type uchar[4])),and my size(255*255*255)
And the cmyk data is all 0.
Then segment fault in func Pack4Bytes.
When debugging it with vscode and gdb ,
I find function  _cmsHandleExtraChannels  didn’t  do anything and return.
And in func “Pack4Bytes” I find that pointer “output ”is void and this func use a “++”operator after it,and it cause the error.
But I don’t  now how to solve it .
I dont now if passing  a wrong type of parameter or any other reason cause the error.
If you need photos and other information (logs ..),please ask me .
I will sincerely appreciate you if you can help me.

**Comment by keerm-code** [comment]
emm I forget to say my OS is Ubuntu 20.10 ,using kernel 5.8.0-46

**Comment by keerm-code** [comment]
In fact I didn`t know what is the param "size " means . I think maybe bug is form it.

**Comment by mm2** [comment]
Could you please post the piece of code that generates the error?
I mean your code, what are you using to call lcms functions.
Thanks, it is very difficult to spot where the bug is blindly.

**Comment by keerm-code** [comment]
//I use cms with opencv mat.
#include"lcms2_plugin.h"
#include"opencv4/opencv2/opencv.hpp"

using namespace cv;

    typedef struct { cmsUInt8Number  r, g, b;    }  RgbArray;
    typedef struct { cmsUInt8Number  c, m, y,k;    }  CmykArray;


    Vec3b cmsStructChange2cvVec(RgbArray array)
    {

        return Vec3b(array.b,array.g,array.r);
    }

 void Mat2Vec(const Mat &input,RgbArray **array)
    {
        for(int i=0;i<input.rows;i++)
        {
            for(int j=0;j<input.cols;j++)
            {   
                array[i][j]=cvVec2cmsStruct(*(input.ptr<Vec3b>(i,j)));
            }
        }
    } 
bool Bgr2Cmyk(cv::Mat &src )
{

RgbArray **rgbarray=(RgbArray **)malloc(sizeof(uchar)*src.channels()*src.cols*src.rows);
CmykArray **cmykarray=(CmykArray **)malloc(sizeof(uchar)*(src.channels()+1)*src.cols*src.rows);
// RgbArray *rgbarray[src.cols];
// CmykArray cmykarray[src.rows][src.cols];
for(int i=0;i<src.rows;i++)
{
rgbarray[i]=(RgbArray*)malloc(sizeof(RgbArray[src.cols]));
cmykarray[i]=(CmykArray*)malloc(sizeof(CmykArray[src.cols]));

}
cmsHPROFILE hinprofile, houtprofile;
cmsHTRANSFORM htransform;
uchar rgb[3]={0,0,0};
uchar cmyk[4]={0,0,0,0};
Mat2Vec(src,rgbarray);
hinprofile = cmsOpenProfileFromFile("./config/camerargb.icc", "r");//*打开rgb颜色空间配置文件
houtprofile = cmsOpenProfileFromFile("./config/MyCmyk.icc", "r");//*打开cmyk颜色空间配置文件
if(!hinprofile||!houtprofile)
{
return false;
}
htransform = cmsCreateTransform(hinprofile,
TYPE_RGB_8,
houtprofile,
TYPE_CMYK_8,
INTENT_PERCEPTUAL, 0);
cmsCloseProfile(hinprofile);
cmsCloseProfile(houtprofile);
for (int i=0; i < src.rows
; i++)
{
for(int j=0;j<src.cols;j++)
{
rgb[0]=rgbarray[i][j].r;
rgb[1]=rgbarray[i][j].g;
rgb[2]=rgbarray[i][j].b;

cmsDoTransform(htransform,rgb,cmyk
,
1);
cmykarray[i][j]=CmykArray{cmyk[0],cmyk[1],cmyk[2],cmyk[3]};
}


}
cmsDeleteTransform(htransform);
return true;
}

**Comment by keerm-code** [comment]
//and it is my main.cpp
#include<iostream>
#include"opencv4/opencv2/core.hpp"
#include"opencv2/opencv.hpp"

#include<vector>
#include"cmyktools.hpp"

using namespace cv;
using namespace std;

int main()
{
    VideoCapture v;
    v.open(0);
    if(v.isOpened()==false)
    {
        exit(-1);
    }
    Mat test;
   while(1)
    {
        v>>test;
        
        Mat cmyk,mask;              
        cmyk=test.clone();
        cout<<test.channels()<<endl;
Bgr2Cmyk(cmyk);
        cout<<cmyk.channels()<<endl;
        
        waitKey(); 
        vector<Mat> cmykchan;
        split(cmyk,cmykchan);
        imshow("y",cmykchan[2]);
        imshow("bgr",test);
        imshow("cmyk",cmyk);
        waitKey(1);
    }
}

**Comment by mm2** [comment]
Check cmsCreateTransform() to return a non-null transformation. Maybe your output profile is not a cmyk  one?
Otherwise thos is going to be very slow. It is better to pass to cmsDoTransform() large buffers instead of one pixel at time.
Try icctrans with your profiles to see if they are correct:
  icctrans -i cameragb.icc -o mycmyk.icc

**Comment by mm2** [comment]
assuming you found the error on your code
