### ISSUE TITLE
Consider adding cmsGetStageContextID function

### ISSUE THREAD

**Issue by jrshoare** [mm2/Little-CMS#253]
There is already a cmsGetPipelineContextID function that returns the cmsContext associated with a cmsPipeline. A similar function for cmsStage would allow wrapper code to provide the context that was used when originally creating a stage added to a pipeline.

I have a wrapper class that maintains the context for a stage (and other library types) but when creating an instance for a stage returned by unlinking from a pipeline (cmsPipelineUnlinkStage) it is not possible to determine the original context used to create said stage. By adding the suggested function this would then become possible.

**Comment by mm2** [comment]
A great idea, 
Solved in commit 15e449013ed246ab9a983248e261062ee8a72b7c
Thanks!
