### ISSUE TITLE
fast_float extensions and conversion crashes

### ISSUE THREAD

**Issue by LostVector** [mm2/Little-CMS#254]
Hi,

I'm doing an image operation in extended linear p3 color space and converting the result into sRGB using the fast float extensions.  I'm getting some very odd crashes doing this that don't appear to happen when the fast float extensions are not enabled.

I've been able to stop the crashes by clamping the floating point values from 0 - 1, but that's not really appropriate for all of the image processing I'm doing.

Is it possible there are some range or safety checks that are being bypassed in the fast float extensions?

**Comment by mm2** [comment]
Hello and thanks for reporting.

Do you have any crash dump or reproducible sample? 
I would be glad to solve the issue but not sure where to search.

**Comment by mm2** [comment]
Found a possible cause, which is NAN and de normal values in the input data. After commit b423949ac9abcfd4009606856eba39217b3bd9b2 it should not segfault anymore.

**Comment by LostVector** [comment]
Thank you for being so proactive! I have not had time yet to try and pull the data/repro case out of my test harness into a simpler test case, so I just mentioned it in case it rang any bells, which it sounds like it might have.  I will work on integrating the new code and seeing if the crashes are still happening later this week.

**Comment by LostVector** [comment]
My test designed to induce the crash is now passing after the latest github commit.  Great catch!!!

I will close this issue for now and report back if we see any other instabilities.
