### ISSUE TITLE
Segfault in fast_float_tethra.c

### ISSUE THREAD

**Issue by butcherg** [mm2/Little-CMS#260]
Running my software rawproc in gdb, encountered this:

```
Thread 25 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8356.0x2bc8]
0x00007ff7bcecffd7 in FloatCLUTEval (CMMcargo=<optimized out>,
    Input=0x1f95f151f00, Output=0x1f95f151f00, PixelsPerLine=6064,
    LineCount=505, Stride=0xa60cbff7a0)
    at ../../../../plugins/fast_float/src/fast_float_tethra.c:191
```
I couldn't get to the code without killing the program, so I couldn't look up values being passed to DENS.  My code was calling cmsDoTransformLineStride(), with TYPE_RGB_FLT for both input and output.

**Comment by mm2** [comment]
Hey, thanks! This actually has been of great help, as it made me suspicious about the nature of the data being feed to the transform. After some investigation I found NAN and subnormal values of floating point numbers can segfault, but only if compiled under gcc, this does not happen on windows visual studio. I have modified the code to add check guards and added a test case in the automated testbed. Should not segfault anymore. Anyway I'm keeping this issue open for a while until I could confirm this solution work fine for everybody.

Thanks for reporting and helping to solve this very elusive bug!

**Comment by butcherg** [comment]
Just pulled master, compiled it, and relinked it into rawproc.  I do hundreds of cmsTransforms every week in my display transform and I'm currently running in gdb to debug my own segfaults, so if there's a latent something I should see it.

You're welcome; glad to contribute.

**Comment by mm2** [comment]
No news, good news so I'm closing the issue. Please feel free to reopen it if you find any other segfault.
