### ISSUE TITLE
Need #include <stdint.h> in tificc.c

### ISSUE THREAD

**Issue by butcherg** [mm2/Little-CMS#269]
Just updated my fork, tried to rebuild, and got a lot of these:

`../../../utils/tificc/tificc.c:36:18: error: unknown type name ‘uint16_t’; did you mean ‘u_int16_t’?`

Added #include <stdint.h> at the top of tificc.c, all got well.  I'd submit a patch, but the change is trivial and you probably would want to place it appropriately in the file...

**Comment by mm2** [comment]
Fixed per c8ae6fbba1d387a686786bf801038a318e45d8a1
