### ISSUE TITLE
fast_float: RGB => L*a*b* (8 bits/channel) gives wrong colors

### ISSUE THREAD

**Issue by Lynx3d** [mm2/Little-CMS#272]
Something seems to be wrong in Optimize8BitRGBTransform() in fast_8_tethra.c.

When converting from RGB/Alpha (sRGB profile) to L\*a\*b\*/Alpha, both 8 bits/channel, the mentioned optimization gets used and the result looks like this:
https://krita-artists.org/t/krita-5-0-beta-lab-a-color-space-bug-regress/27722
(That's supposed to be HSV color selector)

If either (or both) of the color spaces is >8 bits depths, there seems to be no problem.

**Comment by hallarempt** [comment]
Ping? If we cannot have a fix for this in littlecms, we're going to have to disable the fast_float plugin in Krita again :-( We're having a bunch of bugs:

https://bugs.kde.org/show_bug.cgi?id=441959 
https://bugs.kde.org/show_bug.cgi?id=441366

**Comment by mm2** [comment]
I have merged a PR that probably would fix that bug (it seems the same on both references)

**Comment by Lynx3d** [comment]
I'm not sure which PR you're referring to, but mine only fixed alpha channel issues, and a fresh master build still has the issue described here.

**Comment by hallarempt** [comment]
We don't have PR for the lab problem, do we?

**Comment by Lynx3d** [comment]
No, I don't know enough about these optimizations to propose a fix, I was just able to verify  that just disabling the Optimize8BitRGBTransform() optimization for RGB => Lab case resolves the issue, at the cost of performance, I assume.

**Comment by mm2** [comment]
The PR from Lynx3d fixed the bug 441959 (Thanks Lynx3d , great job!)
Commit c07b7e363cd4ea188876b6aa8f0357c0f0b8d0cb fixes 441366

>Ping? If we cannot have a fix for this in littlecms, we're going to have to disable the fast_float plugin in Krita again :-( We're having a bunch of bugs:

Please  file one different LittleCMS issue for each problem, otherwise it is hard to me to assess the real severity. Fixing time is about one month, maybe less if you are lucky or more if the issue is complex. I have been a contributor of Krita from the very beginning and I'm glad to help ASAP, but sometimes I have no available time at all. Keep in mind this is a non-profit project and I have other (paid) tasks to do.

**Comment by Lynx3d** [comment]
Sorry if I gave  the impression that my PR was related to this issue, I hadn't opened an extra issue for the Alpha channel bug that I didn't properly fix the first time, and now see that I also forgot to explicitly mention the original issue report that had been closed meanwhile.

I'll try to do better next time...

In any case, this issue appears to be fixed, thank you!

**Comment by mm2** [comment]
Sorry, the message was intended for hallarempt, not for you.  I can only be grateful for your contributions.
