### ISSUE TITLE
Readouts values after applying ICC profile are wrong

### ISSUE THREAD

**Issue by wisdomk** [mm2/Little-CMS#274]
I am trying to use LittleCMS library in my workflow and I was looking whether the distinction between "Assigning vs. Convert to ICC profile" exists in the library functionality. However, I've found no clear statement that defines which exactly LittleCMS cmsDoTransform() prefers doing and based on some inspections by taking the profile and importing it into GIMP then trying both options "Assigning/Converting to" on a photo . The readouts values after using "Assign" seems to match the output values after using LittleCMS. Hence, I presume LittleCMS is doing profile assigment rather than conversion however it is not the results that I am looking for and I would like to be able to get the values of the "Convert to ICC", any idea if that is a shortcoming of the library or not and how to solve it?

**Comment by butcherg** [comment]
cmsDoTransform() is only about converting an image from one profile's color/tone to another.  "Assign" means to associate a profile with an image, and doesn't really do anything to the image.

In my software, an internal image has a few extra items of information, one of them being a profile.  My colorspace tool has two options, "assign" and "convert", and "assign" stores the specified profile in the variable for that purpose.  Later, if I insert another colorspace tool and select "convert", cmsDoTransform() is called to do the conversion, using the previously assigned profile as the input profile.

**Comment by wisdomk** [comment]
well...I am aware that the only functionality available in LittleCMS is a transformation from one color space to another. 
and you are right assigning means sort of "saving" a profile into the image with consideration that when a certain ICC profile is being assigned it means the colors will be interpreted accordingly (i.e. assigning sRGB profile will results in different colors than assigning AdobeRGB while the underlying pixels' values are supposed to stay unaltered).

However, my problem is that when doing a transformation from source profile to a destination profile the resultant values are not the same when I use the "convert" functionality of GIMP with the same source/destination profiles.

and I am trying to figure out if any additional step should be taken or is taken by GIMP so that the values are different from LittleCMS given the fact that GIMP uses LittleCMS library as a color management engine.

any idea?

**Comment by wisdomk** [comment]
I guess I got what is wrong and got it solved.
so basically I have a tiff photo with camera embedded profile which I am profiling and creating a new color profile out of it (as it is a color checker) in order to apply this newly created ICC on the photo and have more accurate color values. The wrong thing was happening in the transformations basically as I figured out after many hours that I need to do the transformation twice (embedded camera profile -> newly created ICC) then
(newly created ICC -> output ICC e.g. AdobeRGB)

**Comment by butcherg** [comment]
Ah, good you understand 'assign'; your original question didn't read that way to me...

So, you're making camera profiles! That's become a sort of hobby to me, and now I'm wondering about why you're having to do two transforms to get to AdobeRGB.  This is not the correct place to discuss that, but you're welcome to come over to https://discuss.pixls.us and describe what you're doing.

Cheers!
