### ISSUE TITLE
Enhance the cmsFLAGS_COPY_ALPHA for opaque source and transparent destination

### ISSUE THREAD

**Issue by mrserb** [mm2/Little-CMS#281]
The cmsFLAGS_COPY_ALPHA provides a great built-in functionality taking care of the alpha channel. It works fine when the source and destination both have alpha, it also works fine if the destination does not have an alpha(obviously the alpha channel from the source is just discarded). But what about the case when the source does not have an alpha channel but the destination has it? 
Shouldn't littlecms makes the destination and its alpha opaque in that case?

**Comment by mm2** [comment]
If you use a formatter with alpha on output, and you don't use  cmsFLAGS_COPY_ALPHA, the alpha channel is bypassed. That means, you are free to put anything you wish in the output buffer before the color transform, it will NOT touch any value on there. It works in such way to allow user to deal with cases like the one you describe. 
 On the other hand, LittleCMS supports several alpha channels simultaneously. What to do if number of alpha channels does not match? Which default should it use? There are plenty of different encoders. What number is "opaque"? in many systems is 255 but I've seen signed alpha where "opaque" is 127

**Comment by mrserb** [comment]
I agree with you that by default lcms may not have all the necessary information about how to handle different numbers of channels, or absent the alpha in the source when the dst has it. But I guess for the know formats like TYPE_ARGB_8, it is known that the alpha channel is one byte and opaque=255? If it is not known then probably the app may add that hint? For example, the app may suggest the min/max values of the alpha and the lcms may scale that from src to dst based on the min/max values of src/dst.

BTW My next enhancement to ask was about premultiplied alpha. As far as I understand the overall suggestion to use pre-alpha was related to the custom plugin, so maybe the current issue could be solved by such a custom plugin as well. Actually, My goal is to minimize the number of touching "random" pixels in the memory and try to do all work in only one loop.

**Comment by mm2** [comment]
Premultiplied alpha is now implemented. Closing the issue.

**Comment by mrserb** [comment]
@mm2 Is any possible way to inject such functionality via plugins? This plugin needs to implement only one feature that will set the alpha channel in the destination to an opaque value(since it cannot be copied from the source). For now I see only one way to do that is to modify the code of `_cmsHandleExtraChannels` and configure it via some flag.

**Comment by mm2** [comment]
It is easy:
1 - memset of opaque value to all destination buffer
2 - do the transform and NOT use cmsFLAGS_COPY_ALPHA
3 - Done
Actually is faster to memset a huge block of data than selectively put some values and jump. The transform will overwrite the colorant data

**Comment by mrserb** [comment]
The memset will work for some cases but in general, when the pixels and lines may have extra padding bytes, that will make things complicated and at the end will be similar to the cmsDoTransformLineStride +_cmsHandleExtraChannels

**Comment by mrserb** [comment]
I tried different approaches. The `_cmsHandleExtraChannels `called everywhere in LCMS is not public, the internal code in "cmsalpha.c" looks unaccessible in the external plugin.

So it seems that the only generic solution I might implement is to copy most of the "cmsalpha.c" code and update it to always "read" the opaque value(for example opaque byte) from the source and the rest of the code will properly save it to the destination. That covers all current formats supported by the LCMS. But this heavily depends on the internal data, and most probably will be broken if the implementation of "cmsalpha.c" will be changed.

Probably some public customization API can be provided? like split `_cmsHandleExtraChannels` to a few methods and expose some of them in the "lcms2_plugin.h"?

**Comment by mm2** [comment]
Those are library internal functions. Not accessible via API because may change in future. 
Again, your best option is to store whatever you wish in the positions you wish and then instruct lcms to not touch that. You could pack all this functionality in one function and call this function just before cmsDoTransform. 
For instance, there are people using a special channel to encode named colours. They just use extra channels = 1 and handle that channel outside the color manager.

**Comment by mrserb** [comment]
Then that people actually do similar things to what I try to achieve, but in the end, it will be a copy of "cmsalpha.c". Since _cmsHandleExtraChannels/ComputeComponentIncrements/ComputeIncrementsForPlanar/ComputeIncrementsForChunky are all nonpublic, as well as from8toXXX. And these methods are needed to iterate over existing image layouts.

Will stick to this approach then.
