### ISSUE TITLE
ICC profile produces completely different LAB values in Little-CMS vs. Adobe Photoshop

### ISSUE THREAD

**Issue by rsnitsch** [mm2/Little-CMS#285]
I have stumbled upon a v2 ICC profile which behaves totally different in Adobe Photoshop and in LittleCMS (**deltaE 15+**). I guess there's either a bug in Photoshop or in LittleCMS, because the difference is huge. Or I am using Photoshop in a wrong way.

The ICC profile is a camera input profile created via characterization.

The workflow is as follows:
- I make a picture of a color checker chart.
- I open the JPG file with Photoshop. At first I tell Photoshop to keep the embedded Display P3 profile.
- Then I assign the input ICC profile.
- Then I instruct Photoshop to convert to another profile. There I select LAB as target color space and relative colorimetric conversion. I turn off Dithering.

Now... the weird thing I noticed is that the result in Photoshop is drastically different depending on whether I enable black point compensation or not. If I do the conversion _without_ black point compensation, the results closely match the results from LittleCMS. However, if I enable black point compensation within Photoshop, the resulting LAB values are completely different.

On the other hand, if I enable black point compensation in LittleCMS, the values don't even change. That is, LittleCMS produces the same LAB output values with and without black point compensation. In theory, that makes more sense to me, because when converting to LAB, black point compensation should not have any effect. After all, LAB is a device-independent full-gamut color space. Therefore there is, actually, nothing to compensate for, right?

Though it is hard for me to believe that Adobe Photoshop would ship with such a huge bug.

I used the latest LittleCMS release (2.12) and Adobe Photoshop 22.5.1.

###############################

I uploaded the image, the ICC profile and my code here: https://github.com/rsnitsch/lcms2-vs-photoshop

When running my code with or without black point compensation, I get the following output:
```
Field,  Name,   L,      a,      b
1,      brown,  33.8557,        8.97266,        14.3086
2,      skin,   58.6841,        14.543, 19.2734
3,      light blue,     43.9369,        -5.26172,       -19.6992
4,      green,  35.8042,        -12.6562,       19.9063
5,      violet, 46.6605,        5.64064,        -20.0703
6,      turquoise,      62.7635,        -32.1602,       1.00001
7,      orange, 62.2243,        33.6875,        57.2422
8,      blue,   36.849, 7.40625,        -42.4492
9,      light red,      47.6042,        45.1094,        18.8711
10,     violet, 26.9301,        19.7656,        -17.8281
11,     light green,    68.7331,        -27.3438,       55.4805
12,     ocker,  68.5539,        15.7422,        63.9609
13,     blue,   27.7129,        11.4727,        -47.5117
14,     green,  53.174, -39.5156,       30.4258
15,     red,    39.4179,        49.1641,        31.125
16,     yellow, 81.9363,        -0.0195234,     79.5391
17,     pink,   48.7623,        46.5859,        -12.5742
18,     light blue,     47.618, -30.0117,       -26.6172
19,     white,  97.8738,        -6.24609,       4.15625
20,     gray,   79.7534,        -4.06641,       1.33985
21,     gray,   66.8122,        -5.46094,       1.66798
22,     gray,   50.5071,        -3.96094,       1.08204
23,     gray,   34.0702,        -1.92188,       -0.00782001
24,     black,  20.723, -2.08984,       -0.343752
```

These are the resulting Lab values after converting from RGB.

In Photoshop (_without_ black point compensation) I get for the red patch (no. 15) L = 40, a = 49, b = 31 which is almost the same as the output from LittleCMS.

However, in Photoshop _with_ black point compensation I get for the red patch L = 35, a = 56, b = 46 which is totally different. The deltaE is a whopping 17!

###############################

Do you have any idea what is happening here? If possible, please advise how I can make the results from LittleCMS match the results from Photoshop _with_ black point compensation.

**Comment by mm2** [comment]
Thanks for reporting, 
LittleCMS is performing black point compensation based on Adobe's paper, https://www.color.org/adobebpc.pdf
In the paper Lab as destination is not defined. See 7. 2. Estimating the Destination Black Point. So LittleCMS does nothing because, as you well said, this seems more logical.
In any case,  I don't know latest versions, but prior's creative cloud photoshop bypassed its internal color management logic when using Lab color space was used for images. 
Try to use your profile with sRGB or AdobeRGB as output. That should match photoshop.

**Comment by rsnitsch** [comment]
Thank you very much for the quick response. My project is more of a color measurement application, therefore the Lab values are of main interest. I guess, in a colorimetric setting, black point compensation should be disabled anyway.

> In any case, I don't know latest versions, but prior's creative cloud photoshop bypassed its internal color management logic when using Lab color space was used for images.

This could explain other issues that I had from time to time with Photoshop's Lab values. Can you please tell me more about this? How did you notice this? Has this been filed/reported as a bug to Adobe (in other words: is it planned to be fixed or was this a deliberate change by Adobe)? Was this always the case in Photoshop or is this a new behavior that was introduced in some recent Photoshop version?

**Comment by mm2** [comment]
> Can you please tell me more about this? How did you notice this? Has this been filed/reported as a bug to Adobe

Time ago I was the Hewlett-Packard representative at ICC. I noticed because Adobe guys told me. Tis is not a but, but something like a "secret sauce". It is not documented and not handled in the BPC paper.

**Comment by rsnitsch** [comment]
Ok, great. Thanks again for the quick response. I'll close this issue now.

Thank you for developing the LittleCMS engine. It's a great piece of software.
