### ISSUE TITLE
ICCv4 multiProcessElement sampled curves disregard first point (aka. last point form prev. segment)

### ISSUE THREAD

**Issue by zauguin** [mm2/Little-CMS#286]
Take for example the (device link) profile at https://gist.github.com/zauguin/4282391aece378bbc61115e0a5235d2a/raw/6a080552ae208709b3911ec4db27127a911c6b7b/profile.icc

It has a D2B0 tag with a `multiProcessElementsType` with a single `curf` entry. This `curf` has three segments: `-infinity` to `0` is constant `0`, `1` to `infinity` is constant `1`. Between `0` and `1` it has a sampled curve segment with count `1` and the single entry `1.0`. According to the ICC spec, values between `0` and `1` should be interpolated between `0` (the last value of the *previous* segment) and `1`, but Little-CMS maps all values between `0` and `1` to `1` instead.

More generally, Little-CMS always seems to ignore the last value of the previous segment when processing sampled curves.

**Comment by mm2** [comment]
Seems working ok, so I close it.
