### ISSUE TITLE
Application Verifier warns about "Critical section not initialized"

### ISSUE THREAD

**Issue by alvinhochun** [mm2/Little-CMS#289]
https://bugs.kde.org/show_bug.cgi?id=444875

It appears that the critical section is to be initialized in [`cmsCreateContext`](https://github.com/mm2/Little-CMS/blob/0b845e907e63129110e2ce5ee2e4476e7b6efd08/src/cmsplugin.c#L805), but in Krita we never call this function. This leads me to believe that placing the block of code which handles initialization of the critical section inside `cmsCreateContext` is not correct.

**Comment by mm2** [comment]
I have tried to reproduce the issue with no success. The code is called and critical section initialized.
How you managed to get this error?

**Comment by alvinhochun** [comment]
Are you testing with a Krita release? When I enabled the check in Application Verifier and start krita.exe in a debugger I always get the warning when starting up.

**Comment by alvinhochun** [comment]
Thanks for the fix! :)

I can't test it now, but as soon as we update our dependencies to include the fix I will test it and report back.

**Comment by alvinhochun** [comment]
Verified that I no longer get the warning with AppVerifier after updating lcms to 2.13rc2. Thanks again!
