### ISSUE TITLE
tifficc convert problem?

### ISSUE THREAD

**Issue by JohnXu28** [mm2/Little-CMS#294]
Hi Marti,

I'm sorry for disturbing you.
I tried to use tifficc(lcms 2.12) to convert color from "scanner.icc" color space to Lab color space, but I got the wrong output.
I use the following command.
tifficc -o*Lab In.tif out.tif

I found the problem is that when saving to tiff(Lab color space), it needs to do addition process.
**a = a^0x80
b = b^0x80**

p.s. I also use the tifficc(lcms 1.19) to convert the same file and get the correct output image.

**Comment by mm2** [comment]
Fixed, thanks for reporting!
