### ISSUE TITLE
How can I determine if a cmsHPROFILE supports wider-than-sRGB color?

### ISSUE THREAD

**Issue by AttilaTheFun** [mm2/Little-CMS#297]
I'm currently using Little-CMS indirectly from Go via [govips](https://github.com/davidbyttow/govips) > [libvips](https://github.com/libvips/libvips) > [lcms2](https://github.com/mm2/Little-CMS).

I'm developing a service that takes images uploaded by users and normalizes their representation in terms of file format and color profiles. I want to normalize images with wide color profiles like Display P3, Adobe RGB, Pro Photo RGB (as well as RAW images) to the Display P3 color profile, and images with an sRGB profile or no profile to the sRGB IEC61966-2.1 profile.

I do this because iOS and macOS devices have supported Display P3 with wide color displays since the iPhone 7 (2016), and basically any device can display sRGB images. (I actually produce an sRGB version of all of the images for use on devices without wide color displays.)

Right now I'm using [prism](https://github.com/mandykoh/prism) to parse the name of the ICC profile and then basically switching over a set of known profiles to determine if the image is a wide color image. Ideally I'd like to handle this "correctly" by actually extracting the embedded cmsHPROFILE and querying it to see if it has a wide color gamut. This would be less brittle and would work with a wider variety of color profiles.

Is there already some kind of API like this?

```
CMSAPI cmsBool           CMSEXPORT cmsProfileSupportsWideColor(cmsHPROFILE hProfile);
```

If not, how could I determine that? And if this information is only internal, could we potentially expose an API to query this? Thanks!

**Comment by butcherg** [comment]
Anyone more knowledgeable about this than I is welcome to swat me...  :)

If you're familiar with the chromaticity plots, you know that they're triangles based on vertices made from the x and y components of the xyY coordinates of the color primaries..  You could calculate the area of the triangle of the profile in question, and compare that number to the area of the sRGB primaries.

From the LittleCMS API documentation, you can use cmsReadTag() to read the cmsSigRedMatrixColumnTag, cmsSigGreenMatrixColumnTag, and cmsSigBlueMatrixColumnTag, which returns cmsCIEXYZ structures. Convert each XYZ to xyY, then use the xy components to compute a geometric area.

**Comment by AttilaTheFun** [comment]
I'm admittedly not super familiar with the math involved. 😅
I was kinda hoping there was a simpler way, but that does make sense.
You're suggesting basically comparing the area of the input image's color profile vs. a generic sRGB profile to see if it's larger? I suppose that works. 
I'll give the other contributors a little while to weigh in, but if they don't have any better ideas I can give that a shot.

**Comment by butcherg** [comment]
XYZ to xyY is pretty simple:

http://www.brucelindbloom.com/index.html?Eqn_XYZ_to_xyY.html

Then, the area under a triangle where the length of the three sides is known is also rather simple:

https://en.wikipedia.org/wiki/Heron%27s_formula

**Comment by AttilaTheFun** [comment]
Thanks for the help! I've got to do some plumbing to extract and decode the cmsHPROFILE first, but once I do I'll give that a shot. Probably won't have time till this weekend, though.

**Comment by mm2** [comment]
That's easy with the help of softproofing & gamut check. Do't mess with the tags  or primaries directly, as that would work only on matrix-shaper profiles. Please consider this code instead:

```
static int total_colors;
static int out_of_gamut_colors;

cmsInt32Number sampler(CMSREGISTER const cmsUInt16Number In[],
                        CMSREGISTER cmsUInt16Number Out[],
                        CMSREGISTER void* Cargo)
{
    cmsHTRANSFORM xform = Cargo;
    cmsUInt8Number out_of_gamut;

    cmsDoTransform(xform, In, &out_of_gamut, 1);
    total_colors++;
    if (out_of_gamut > 0)
        out_of_gamut_colors++;

    return TRUE;
}


cmsBool ProfileSupportsWideColor(cmsHPROFILE hProfile)
{
    static const int array33[] = { 33, 33, 33 };
    cmsHPROFILE hsRGB = cmsCreate_sRGBProfile();
    cmsHPROFILE hNull = cmsCreateNULLProfile();

    cmsHTRANSFORM xform = cmsCreateProofingTransform(hProfile, TYPE_RGB_16, hNull, TYPE_GRAY_8,
        hsRGB, INTENT_RELATIVE_COLORIMETRIC, INTENT_RELATIVE_COLORIMETRIC, 
        cmsFLAGS_SOFTPROOFING | cmsFLAGS_GAMUTCHECK | cmsFLAGS_NOOPTIMIZE);

    total_colors = out_of_gamut_colors = 0;
    cmsSliceSpace16(3, array33, sampler, xform);

    cmsCloseProfile(hNull); cmsCloseProfile(hsRGB);
    cmsDeleteTransform(xform);

    if (((out_of_gamut_colors * 100) / total_colors) > 2)
        return TRUE;

    return FALSE;
}

```

I'm using the NULL profile, which is a profile that returns 0 for all input. In this way, only colors marked as out of gamut got a value different from zero. I use 2% of colors out of gamut to mark profile as not encompassing. There is no error checking as this is only as example, you have to add your own for production code. Hope that helps.

**Comment by AttilaTheFun** [comment]
Awesome, thanks! I'll try that tomorrow.

**Comment by butcherg** [comment]
That's a lot better that what I was going to write...   :)

Marti, I recently noticed this in the build of my current rawproc version, I just included -Wno-register in my build and made a note to report it, which I lost, but here 'tis:

```
warning: ISO C++17 does not allow ‘register’ storage class specifier [-Wregister]
   13 | cmsInt32Number sampler(CMSREGISTER const cmsUInt16Number In[],
```

from this compiler:

`gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2)`

**Comment by butcherg** [comment]
Ah, I see that now in page 8 of the API doc...  It might help C++ users of the library who don't want to mess with the source to add an instruction to use -Wno-register to their compiling that #includes lcms.h, as the warning shows up in their compilation...

One more thing regarding this thread, I get this:

error: invalid conversion from ‘const int*’ to ‘const cmsUInt32Number*’ {aka ‘const unsigned int*’} [-fpermissive]

 for the call to cmsSliceSpace16; change the declaration of array33 to static const cmsUInt32Number fixes it.
