### ISSUE TITLE
fast_float: YCbCr (8 bits/channel) is also incompatible

### ISSUE THREAD

**Issue by amyspark** [mm2/Little-CMS#298]
Hi!

I'm writing to let you know that as part of [Krita MR !1300](https://invent.kde.org/graphics/krita/-/merge_requests/1300), we discovered that the fast float plugin is also incompatible with 8-bit/channel YCbCr. This looks like another corner case of #272.

**Comment by mm2** [comment]
Thanks. I have tested the profile and found it to work fine. The fast float plug-in doesn't even take it because the YCbCr space, so the issue its completely unrelated to the plug-in. Otherwise The profile works fine to me... could you explain what is is going wrong?

**Comment by amyspark** [comment]
I'm not exactly sure of the LCMS specifics, @mm2. I've found that on Windows and macOS, where we ship the fast-float plugin, the Advanced Color Selector renders the space completely wrong (the chroma wheel is grossly quantized into just 3 stages). Disabling the fast-float plugin makes it be rendered properly again.

I checked this with our latest nightly, LCMS commit 67d6968f8ff00e9134a574ae919b7360f1d8ec94. Will try later if a library update resolves it.

**Comment by amyspark** [comment]
Update: commit ca7d833d54c164311d32cf842b6e08216cf1467c shows the same behaviour of a truncated chroma wheel:

![imagen](https://user-images.githubusercontent.com/13498015/150768422-66af3d06-af68-4e40-845a-9d10c7e4823c.png)

Again, disabling the fast-float plugin, or adding a check against `PT_YCbCr` here:

https://github.com/mm2/Little-CMS/blob/ca7d833d54c164311d32cf842b6e08216cf1467c/plugins/fast_float/src/fast_8_tethra.c#L367-L368

is enough to fix it.

**Comment by mm2** [comment]
Ah, ok. It is certainly possible this is already solved in 2.13, at least I cannot reproduce it.

**Comment by amyspark** [comment]
@mm2 did you check with the "YCbCr 601 to Lab colorspace conversion profile" and "YCbCr 709 to Lab colorspace conversion profile" profiles that were (formerly) available at your site? Both should suffice to reproduce it.

**Comment by mm2** [comment]
You are right. The optimization only works on RGB8 to RG8 LUTs, so I fixed the code. Thanks for reporting. Should be fixed right now.

**Comment by amyspark** [comment]
Fixed in fac0411e85ab1c84b71c06dd2328553eef0618d0
