### ISSUE TITLE
Let me ask you a light question. (visual studio version)

### ISSUE THREAD

**Issue by cepiloth** [mm2/Little-CMS#300]
Hello. mm2. 
long time no see and happy new year 👍 

I Have some questions.

First, 
It has been confirmed that Visual Studio 2020 is supported in the website content.
https://littlecms.com/blog/2022/01/28/lcms2-2.13/ 
But, I think it's visual studio 2022.

Second,
I want to know the revision of the fixes reported by fuzzer.

thank you:)

**Comment by mm2** [comment]
ups, sorry, a typo in the change log. I will fix it in the site, thanks for let me know!

**Comment by mm2** [comment]
Forgot your 2nd question

> I want to know the revision of the fixes reported by fuzzer.

ab5029d60d5dc41a414e4acc472d024e3449d36a

**Comment by cepiloth** [comment]
thx~
