### ISSUE TITLE
Resulting image is broken

### ISSUE THREAD

**Issue by ademmler** [mm2/Little-CMS#304]
Hi folks,

in a sample project I try to implement littlecms in an QT App.
As Marti described here.(https://littlecms.com/blog/2020/12/09/using-lcms2-on-qt/)

The sample project you can get here:
http://code.ademmler.com/GraphicsViewerCMS.zip

Here is what the resulting image looks like:
http://code.ademmler.com/gvimg01.png

Regards & Thx Alex

**Comment by mm2** [comment]
Did you get my mail?

This program does not work because you missed the part on https://littlecms.com/blog/2020/12/09/using-lcms2-on-qt/ that says:

>  Alpha channels are supported as long as the image is not using premultiplied alpha. To get alpha channel make sure to include cmsFLAGS_COPY_ALPHA in the flags field. This is explained in LittleCMS documentation.

So, try:

```
toDisplay = colorManage(sourceImage, profiles, INTENT_PERCEPTUAL, cmsFLAGS_COPY_ALPHA);
```

This fixed the issue for me.

**Comment by ademmler** [comment]
Dear Marti,

You gave me the perfect hint - superb! if you like  my simple sample put it to your article please.

No email yet - I checked also my Spamfilter.

Regards Alexander
