### ISSUE TITLE
valgrind reporting error on ICC profile

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#315]
Hello! 
I'm back with another fuzzer issue :)

My jpeg 2000 codec fuzzer reports a valgrind error :

```
==1152967== Conditional jump or move depends on uninitialised value(s)
==1152967==    at 0x484C13E: bcmp (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1152967==    by 0x4C4FBE2: CachedXFORM (cmsxform.c:537)
==1152967==    by 0x4C4EFAF: cmsDoTransform (cmsxform.c:206)
```

when the following code executes the transform generated from the profile :

```
auto in_prof = cmsOpenProfileFromMem(icc_profile_buf, icc_profile_len);
auto out_prof = cmsCreate_sRGBProfile();
auto out_space == cmsSigRgbData;
auto in_type = TYPE_RGB_8;
auto out_type = TYPE_RGB_8;
auto intent = cmsGetHeaderRenderingIntent(in_prof);
auto transform = cmsCreateTransform(in_prof, in_type, out_prof, out_type, intent, 0);
auto nr_samples = 1048576;
auto inbuf = new uint8_t[nr_samples];
auto outbuf = new uint8_t[nr_samples];
memset(inbuf,0,componentSize);
memset(outbuf,0,componentSize);
cmsDoTransform(transform, inbuf, outbuf, (cmsUInt32Number)componentSize);
```

The attached zip file has both the JPEG 2000 file, and the extracted ICC profile.

[icc.zip](https://github.com/mm2/Little-CMS/files/8457825/icc.zip)

It could be that the ICC profile was truncated and there are bytes missing. Hopefully it's possible to validate
the profile in this case and avoid conditional jump error.

Thanks in advance for taking a look.

**Comment by mm2** [comment]
I may be wrong but assuming **componentSize** is the number of pixels, and pixel is RGB of 8 bits, doing
```
auto inbuf = new uint8_t[nr_samples];
auto outbuf = new uint8_t[nr_samples];
memset(inbuf,0,componentSize);
memset(outbuf,0,componentSize);
cmsDoTransform(transform, inbuf, outbuf, (cmsUInt32Number)componentSize);
```

memset leaves 2/3 of buffers bytes uninitalized, isn't that what valgrind complains? 

Shouldn't  be that? 

`memset(inbox, 0, nr_samples)`

**Comment by boxerab** [comment]
oops, yes you're absolutely right! sorry for the noise.
