### ISSUE TITLE
[Question]: About spot color opacity(composed of Lab)

### ISSUE THREAD

**Issue by diuming** [mm2/Little-CMS#326]
I have a question about CIE Lab color.
How do I calculate percentage of spot color(composed of CIE Lab)?
It's a personal question, You can ignore.

for example,
<!DOCTYPE html>

|  | L | a | b | Status | Opacity |
| --: | --: | --: | --: | --: | -- |
| 100% | 55.6 | 2.1 | -40.4 |   | 0 | 
| 75% | 71.5 | 0.2 | -24.6 | computed | 25 | 
| 40% | 83.1 | -0.7 | -14.8 | computed | 60 | 
| 30% | 87.4 | -0.6 | -10.9 | computed | 70 | 
| 20% | 91.7 | -0.5 | -7.2 | computed | 80 | 
| 10% | 95.9 | -0.3 | -3.5 | computed | 90 | 

How do I calculate 50% Lab values from 100% Lab values?
Anyone could give me advice?

thanks

**Comment by mm2** [comment]
Opacity is not colorimetric. It depends on the color space and media. Your best option is to convert from lab to any synthetical RGB space, sRGB for example, perform the blending/opacity and then back to Lab.  Little CMS supports alpha blending so you could do it with few lines of code.

**Comment by mm2** [comment]
If you wanna take a step further, there are differential equations that may help. Do a search on "Kubelka-Munk".

**Comment by diuming** [comment]
I got it, thank you for helping me.
