### ISSUE TITLE
[Question]: How do I verify spectral reflection value scale is 0-1.0 or 0-100.0 in CGATS?

### ISSUE THREAD

**Issue by diuming** [mm2/Little-CMS#327]
I get a spectral(380nm to 730nm) reflection values saved in CGATS file.
according to i1Profiler it can be saved as 0-1.0 or 0-100.0 value scale.
How do i verify the reflection value scale is 0-1.0 or 0-100.0?

If I known the maximum reflection value maybe can resolve this problem. if so.
For example:
The maximum reflection value is 1.5 any value over it denote the value scale is 0-100.0.

Is there a defined reflection maximum value?

Could you give me any advice?

thanks

**Comment by mm2** [comment]
This is a question to do to iProfiler guys. CGATS parsing done by Little CMS is just syntactic. How to interpret the data, the semantics, is entirely up to you.

**Comment by diuming** [comment]
I got it, thank you for helping me.
