### ISSUE TITLE
Black point adaptation in relative colorimetric intent?

### ISSUE THREAD

**Issue by haasn** [mm2/Little-CMS#328]
I noticed that your code does not seem to do any sort of black point compensation for relative colorimetric intent. Can you help me understand the reasoning behind this limitation, and suggest what else I should be doing instead?

My problem statement is as follows: I have a source image with known (fixed) colorimetry metadata, represented in absolute brightness units (e.g. PQ) with fixed and known white and black point, say 200 nits white and 0.2 nits black. **I can already guarantee that these fixed white/black points are very close, but not exactly equal to, the display characteristics**. (In particular, the fixed black point is always true neutral (D65), whereas the display's black point may be off-neutral.) I want to adapt this to a display ICC profile, with minimal further distortion.

If I simply construct a synthetic ICC profile representing the source (e.g. using parametric tone curve `2` with gamma=1, a=(white-black) and b=black), and create a transform linking these two together, then I get worse results the further my display black point deviates from D65. I noticed that `cmsFLAGS_BLACKPOINTCOMPENSATION` flag is ignored in relative colorimetric intent - an input of 0/0/0 to the transform might come out as 0.01/0.02/0.005 instead.

Would it be possible to construct something which works like relative colorimetric but uses whatever slight adjustment is necessary to ensure black continues mapping to black? Or is this what the perceptual intent is all about, and I should really be hard-coding that, even for profiles which have "relative intent" as their preferred intent in the header? (And how do the "preserve_k" intents tie into this?)

The reason I am not using perceptual intent currently is because I want to avoid further subjective distortion - subjective black point adaptation (e.g. going from 0.005 nits to 0.2 nits) has already been performed by this stage. My understanding is that the perceptual tables may contain arbitrary subjective mappings, including gamut stretching or implicit gamma drops for the environment, etc.

**Comment by mm2** [comment]
> I noticed that your code does not seem to do any sort of black point compensation for relative colorimetric intent. 

Lcms black point compensation works fine, but It is exactly the opposite. BPC does very little on perceptual and may have a strong effect on relative colorimetric. Of course profiles have to be suitable to do that and the profile you have built probably is not.

Do this to check it:

By using transicc or your code, with the relative colorimetric intent without nothing else, convert from RGB (0, 0, 0) to Lab. You should obtain the Lab of media black, with a L* of something greater that 4 and a*/b* close to zero.
If this is the case, then you could check the monitor profile as well. Should work alike, but with L* bigger. 

Then, if you do black point compensation that means that (0, 0, 0) from origin space have to map to (0, 0, 0) of monitor, which means blacks are matched in addition to whites. Probably this is not what you want. I would instead try a simple transform with V4 absolute colorimetric intent.

**Comment by haasn** [comment]
So, I have run a number of tests to illustrate my issue:

* [input.icc](https://0x1.st/id.icc)
* [display.icc](https://0x1.st/iz.icc)

All tests were run on an input value of 0/0/0.

### Input/Display -> Lab (without BPC)

```
$ transicc -t 1 -i input.icc -o '*Lab'
L*=0.8268 a*=0.0000 b*=-0.0000 

$ transicc -t 1 -i display.icc -o '*Lab'
L*=0.8270 a*=0.0091 b*=-0.0146 
```

As you say, this gives us the true values (which are similar, but not equal - as I described, my display ICC profile is *not* quite neutral)

### Input/Display -> Lab (with BPC)

```
$ transicc -b -t 1 -i input.icc -o '*Lab'
L*=-0.0000 a*=0.0000 b*=-0.0000 

$ transicc -b -t 1 -i display.icc -o '*Lab'
L*=-0.0000 a*=0.0091 b*=-0.0146 
```

As you state, this *does* match 0/0/0 onto L*=0, as intended.

### Input -> Display (with and without BPC)

```
$ transicc -t 1 -i input.icc -o display.icc
Red=3.0039 Green=4.8288 Blue=1.3152 

$  transicc -b -t 1 -i input.icc -o display.icc
Red=3.0039 Green=4.8288 Blue=1.3152 
```

As I claim, however, you can clearly see that the `-b` flag does *not* affect the transformation from `input` to `display` at all, and `0/0/0` in the input profile fails to map to `0/0/0` in the display profile.

### Input -> Display (perceptual intent)

```
$ transicc -t 0 -i input.icc -o display.icc
Red=13.8755 Green=14.3074 Blue=13.3891 

$ transicc -b -t 0 -i input.icc -o display.ic
Red=0.0000 Green=0.0000 Blue=0.0000 
```

As you can also see, black point compensation does something seemingly only for the perceptual intent.

This exactly reproduces the issue I was raising in the OP.

**Comment by mm2** [comment]
Those profiles are wrong. I have not analyzed the profiles in depth but at first glance profile iz.icc does not roundtrip on relative colorimetric on low values. Also profile id.icc claims V4 and returns a black point over perceptual black. 

You can easy see they are wrong here:

> $ transicc -t 0 -i input.icc -o display.icc
> Red=13.8755 Green=14.3074 Blue=13.3891 

Good profiles should match (0, 0, 0) to (0, 0, 0) on perceptual.

Regarding BPC, I have checked to do this with Photoshop and behaves exactly the same. Same numbers. On perceptual Photoshop always does BPC to hide profile defects like those you see. At least in CS4 which is the version I'm testing.

**Comment by haasn** [comment]
Interesting notes. `iz.icc` comes from a user bug report and was generated by `DisplayCAL`, while `id.icc` is generated with Little-CMS:

```c
    float b = powf(icc->csp.hdr.min_luma / icc->csp.hdr.max_luma, 1.0f / icc->gamma);
    float a = (1 - p->b);
    cmsToneCurve *curve = cmsBuildParametricToneCurve(p->cms, 2,
            (double[3]) { icc->gamma, p->a, p->b });
    if (!curve)
        goto error;

    cmsCIExyY wp_xyY = { best->white.x, best->white.y, 1.0 };
    cmsCIExyYTRIPLE prim_xyY = {
        .Red   = { best->red.x,   best->red.y,   1.0 },
        .Green = { best->green.x, best->green.y, 1.0 },
        .Blue  = { best->blue.x,  best->blue.y,  1.0 },
    };

    p->approx = cmsCreateRGBProfileTHR(p->cms, &wp_xyY, &prim_xyY,
                        (cmsToneCurve *[3]){ curve, curve, curve });
    cmsFreeToneCurve(curve);
```

**Comment by mm2** [comment]
I suspect the issue comes from id.icc, which returns a non-zero black point but below perceptual black. V4 ICC profiles are tricky, when using perceptual PCS they should conform to some conventions regarding black. See ICC spec 4.4.0 Annex D.2.2 and 6.3.4.3 PCS encodings for white and black6.3.4.3 PCS encodings for white and black. 
If I instead use the V4 srgb built-in all works as expected.

**Comment by haasn** [comment]
> V4 ICC profiles are tricky, when using perceptual PCS they should conform to some conventions regarding black.

Ah, yes, I see it now - the presence of `cmsPERCEPTUAL_BLACK` as well. But this leaves me wondering - since I don't *want* any perceptual mapping (i.e. I want to use relative colorimetric intent throughout), s there any way I can generate a *non-perceptual* profile using Little-CMS built-ins?

It seems like `cmsCreateRGBProfile` always creates a V4 perceptual profile? Even if I change the header intent, it doesn't do anything. I feel like I'm in a bit over my head here, and starting to question whether I shouldn't just use a `Lab` input profile, and implement my own black point compensation algorithm instead of trying to construct an RGB source profile at all, because it seems like there are so many moving parts and brittle combinations.

**Comment by mm2** [comment]
It happens that the profile has only one intent and this intent is perceptual no matter what header says. 

Try this when creating the id.icc profile and before saving it 
`cmsSetProfileVersion(hProfile, 2.2)
`
V2 profiles are allowed to use any black point in perceptual. Since iz.icc is also V2 I guess it will work.

**Comment by haasn** [comment]
> Try this when creating the id.icc profile and before saving it

This creates https://0x1.st/i1.icc which has the exact same output as the V4 profile above (id.icc).

**Comment by haasn** [comment]
I suspect that the root issue here is, unavoidably, the fact that the generated profile doesn't round-trip its own measured black point back to `0/0/0`.

**Comment by mm2** [comment]
Turned to be a profile issue, closing
