### ISSUE TITLE
SEGV in `cmsstrcasecmp /lcms/src/cmserr.c:44`

### ISSUE THREAD

**Issue by kobrineli** [mm2/Little-CMS#337]
Hi! I already created an issue #333, but in corresponding commit 00a657c335e1452baeb7eed26c0988a5d2bd75f6 only error in `cmscgats` was fixed, and error in `cmserr.c:44` is still not fixed, so I reopen the issue.

### Steps to reproduce

1. Build docker container from https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/lcms

        sudo docker build -t oss-sydr-fuzz-lcms .

2. Run docker container and run target on attached input [crash-4e409a21f06e4fe83edf2b57de480d34505564ce.txt](https://github.com/mm2/Little-CMS/files/9444985/crash-4e409a21f06e4fe83edf2b57de480d34505564ce.txt)

        sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-lcms /bin/bash
        /lcms_fuzz/cmsIT8_load_fuzzer crash-4e409a21f06e4fe83edf2b57de480d34505564ce.txt

3. You will see following outputs:

        cmscgats.c:1539:49: runtime error: implicit conversion from type 'unsigned long' of value 6933332536 (64-bit,     unsigned) to type 'cmsUInt32Number' (aka 'unsigned int') changed the value to 2638365240 (32-bit, unsigned)
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior cmscgats.c:1539:49 in 
        cmserr.c:44:12: runtime error: load of null pointer of type 'const unsigned char'
        SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior cmserr.c:44:12 in 
        AddressSanitizer:DEADLYSIGNAL
        =================================================================
        ==28==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000360ee1 bp     0x0000005dd0a0 sp 0x7ffdb5545bc0 T0)
        ==28==The signal is caused by a READ memory access.
        ==28==Hint: address points to the zero page.
            #0 0x360ee1 in cmsstrcasecmp /lcms/src/cmserr.c:44:12
            #1 0x351454 in BinSrchKey /lcms/src/cmscgats.c:586:15
            #2 0x351454 in InSymbol /lcms/src/cmscgats.c:807:19
            #3 0x359b97 in SkipEOLN /lcms/src/cmscgats.c:1054:14
            #4 0x340eeb in DataFormatSection /lcms/src/cmscgats.c:1971:13
            #5 0x340eeb in ParseIT8 /lcms/src/cmscgats.c:2207:26
            #6 0x335d3b in cmsIT8LoadFromMem /lcms/src/cmscgats.c:2448:10
            #7 0x335d3b in LLVMFuzzerTestOneInput /lcms/./cmsIT8_load_fuzzer.c:26:22
            #8 0x335d3b in main /afl.cc:36:9
            #9 0x7f93bc49d082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
            #10 0x276b0d in _start (/lcms_afl/cmsIT8_load_fuzzer+0x276b0d)

        AddressSanitizer can not provide additional info.
        SUMMARY: AddressSanitizer: SEGV /lcms/src/cmserr.c:44:12 in cmsstrcasecmp
        ==28==ABORTING

**Comment by mm2** [comment]
Actually I checked this and found it is out ouf sync with head, the docker file refers to commit 1ad1b59b69bb12f93bedf412bd595f4cca69d1f0 whilst head is well ahead of that commit, with changes that probably solves what you are reporting., specially a3ddbb9336f8a5aa94de939959ec95e02eaea1e5

**Comment by kobrineli** [comment]
@mm2 

Updated commit in Dockerfile, checked with input that is attached above, error is still there.

**Comment by mm2** [comment]
Fixed in be25a63be953dbfeef41cfec42550739ba74ea63
