### ISSUE TITLE
cmsFLAGS_COPY_ALPHA does not copy alpha w/ fast float plugin enabled for "Apple Wide Color Sharing Profile"

### ISSUE THREAD

**Issue by calkhaz** [mm2/Little-CMS#343]
Hi there. We noticed the alpha will get 0'd out when the input profile is "Apple Wide Color Sharing Profile" and the fast float plugin is enabled.

We are going from TYPE_RGBA_FLT -> TYPE_RGBA_FLT and "Apple Wide Color Sharing Profile" -> linear if that helps.

Let me know if any other information is needed

**Comment by mm2** [comment]
I am trying to reproduce this, but can't locate such profiles. I've Mac mini M1 with Ventura, a Mac mini with Catalina and iPhone 11 and 13, none of them have Apple Wide Color Sharing profile.icc 
Could type please tele a location where I could download those files? Thanks

**Comment by calkhaz** [comment]
Of course. Thanks for looking into this.

https://shopcounter.imgix.net/images/9a/e9/9ae9e5443a20dd1e1d7cd7fcb329e8e6002e144196895a0fe87bc84a0acc4c3c

**Comment by mm2** [comment]
Thanks. I have checked a transform going from the profile that this image has embedded to linear Rec709 gamma 1.0 with TYPE_RGBA_FLT on both sides and using the fast float plug-in.

It works fine to me. 

Things to check:

- Make sure you are using latest version (2.14)
- Make sure you are feeding non-zero alpha values in input and that you use floats. I assume this JPEG is just a way to give me the profile, not part of the test. 
- Make sure you are using cmsFLAGS_COPY_ALPHA when creating the transform. This is needed either if you use the plug-in or not.

If all that fails, try to convert just one pixel with alpha != 0 and see if the value is correctly propagated to the output. You could use the debugger to trace inside the transform. Not too hard, once transform is calculated, the code that applies it is quite simple. It should take just one 3D interpolation to do the color matching.

**Comment by calkhaz** [comment]
We've been looking into this and it looks like the latest had not compiled in correctly, so we were running on an older version. This issue isn't present on 2.14.

I'll go ahead and close this issue. Appreciate your time!

**Comment by mm2** [comment]
Great, glad you solved it!
