### ISSUE TITLE
The transform result does not use the premultiplied alpha format if alpha equals zero

### ISSUE THREAD

**Issue by mrserb** [mm2/Little-CMS#346]
The new implementation of premultiplied [alpha](https://github.com/mm2/Little-CMS/blob/master/src/cmspack.c#L1710) does not convert the resulting data to the premultiplied format if alpha=zero, but just skips that step and returns data in a straight alpha format.

For example:
1. The incoming data is in the argb_pre format [0,0,0,0]
2. LCMS convert that to the ARGB format [0,0,0,0]
3. Using some color profile the LCMS converts the data to the [18, 14, 20, 0]
4. Since the alpha=0 the LCMS skips conversion to the "pre" format and returns it as is, but [0,0,0,0] should be returned.

I think it is possible to optimize it somehow and skip the conversion of such empty pixels.

**Comment by mm2** [comment]
This is not a bug but a feature. Alpha=0 means "fully transparent" so RGB obtained values are undefined. May be any because any*zero = zero.

Interpretation "fully transparent" value with RGB nonzero is left the alpha composer after color management. Converting to zeros would destroy pixel information, so it is better to keep original values and let the composer to decide. If it just does the alpha formula, it works fine.

**Comment by mrserb** [comment]
Did you follow some specs or documentation which describes why the "RGB obtained values are undefined" if alpha=zero? I mean the color components are mostly destroyed if the alpha is 1, why the zero is specific?

**Comment by mm2** [comment]
For alpha zero you can put whatever. On this post they complain for forcing to zeroThree.js sets Texture RGB values to zero when ALPHA is zero on IOSstackoverflow.comI did choose to keep original values as a way to preserve info, is same wrong that forcing zeros but you can get values back.Message ID: ***@***.***>

**Comment by prrace** [comment]
Sergey is complaining about the PRE-multiplied case.
That means each colour component is multiplied by the alpha component.
If alpha is zero, then the colours should be zero, any other answer is wrong.
I don't see how anyone who asks for this could complain that the colour component is lost since it is exactly what they asked for.

**Comment by mm2** [comment]
In premultiplied alpha with alpha zero, if you try to recover the original value you got a division by zero. 
So RGB values means nothing there. ANY value would be fine. I don't see the need to put zeros. Moreover, zero may be interpreted as a black color that was not originally there. And there are other spaces aside RGB. It is safer just to keep the original value and let the composer to do whatever it wishes.

**Comment by mrserb** [comment]
I am not sure that setting it to zero" is same wrong that forcing zeros" since zero is behavior which is required by the premultiplied alpha doc/spec. And behavior on the link you posted above actually follow that, no? 

Do you know any docs mentioned that "ANY value would be fine." for such pixels?

1. Same logic (all zero) are used on windows by some libaries:

> Fully transparent objects no longer have any color at all, so there is only one value that represents 100% transparency: RGB and alpha all zero. 

https://microsoft.github.io/Win2D/WinUI3/html/PremultipliedAlpha.htm

2. The w3c png spec:

> In valid premultiplied data, the sample values never exceed their corresponding alpha values, so the result of the division should always be in the range 0 to 1. If the alpha value is zero, output black (zeroes).

https://www.w3.org/TR/png/#12Alpha-channel-creation

3. The wiki page explicitly say that:

> Ordinary interpolation without premultiplied alpha leads to RGB information leaking out of fully transparent (A=0) regions, even though this RGB information is ideally invisible. When interpolating or filtering images with abrupt borders between transparent and opaque regions, this can result in borders of colors that were not visible in the original image. Errors also occur in areas of semitransparency because the RGB components are not correctly weighted, giving incorrectly high weighting to the color of the more transparent (lower alpha) pixels. 

And the premultiplied alpha does not have that issue, since that is the purpose of the pre format.

4.

I am also not sure that all composers will work as you described, since behavior of the next straight alpha:
```
dst.r = src.r * src.a + dst.r * (1.0 - src.a);
```
is not equal to the next premultiplied alpha
`dst.r = src.r + dst.r * (1.0 - src.a);`
If src.r is not multiplied by the src.a already.

**Comment by mrserb** [comment]
I am not sure that setting it to zero" is same wrong that forcing zeros" since zero is a behavior which is required by the premultiplied alpha doc/spec. And API on the link you posted above actually follow that rule, no? 

Do you know any docs mentioned that "ANY value would be fine." for such pixels? There are many docs mentioned the opposite.

1. Win2D on windows:

> Fully transparent objects no longer have any color at all, so there is only one value that represents 100% transparency: RGB and alpha all zero. 

https://microsoft.github.io/Win2D/WinUI3/html/PremultipliedAlpha.htm

2. The w3c png spec:

> In valid premultiplied data, the sample values never exceed their corresponding alpha values, so the result of the division should always be in the range 0 to 1. If the alpha value is zero, output black (zeroes).

https://www.w3.org/TR/png/#12Alpha-channel-creation

3. The wiki page explicitly say that:

> Ordinary interpolation without premultiplied alpha leads to RGB information leaking out of fully transparent (A=0) regions, even though this RGB information is ideally invisible. When interpolating or filtering images with abrupt borders between transparent and opaque regions, this can result in borders of colors that were not visible in the original image. Errors also occur in areas of semitransparency because the RGB components are not correctly weighted, giving incorrectly high weighting to the color of the more transparent (lower alpha) pixels. 

And the premultiplied alpha does not have that issue, since that is the purpose of the pre format.

4. Some mit coursers.

>The presentation of the rules is simplified if we assume that each pixel’s RGB value is premultiplied by its alpha value.  For opaque pixels (A=1), this has no effect; for transparent pixels (A=0), this sets the RGB value to 0.

https://courses.csail.mit.edu/6.831/archive/2008/lectures/L20-alpha-compositing/L20-alpha-compositing.html

But it did not found something that mentioned that converting to the pre alpha can skip multiplication by zero.

I am also not sure that all composers will work as you described, since behavior of the next straight alpha:
```
dst.r = src.r * src.a + dst.r * (1.0 - src.a);
```
is not equal to the next premultiplied alpha
`dst.r = src.r + dst.r * (1.0 - src.a);`
If src.r is not multiplied by the src.a already.

**Comment by mrserb** [comment]
Some useful documentation on why the color does actually matter in the transparent images:
http://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/

And another example: https://tomforsyth1000.github.io/blog.wiki.html#%5B%5BPremultiplied%20alpha%5D%5D

> Consider a semi-translucent texture with a variety of colours in it. With conventional blending, the colour of alpha=0 texels is irrelevant you think - because hey - they get multiplied by alpha before being rendered. But it's not true - consider when the bilinear filtering is half-way between RGBA texels (1,0,0,1 = solid red) and (0,0,1,0 = transparent blue). The alpha value is obviously interpolated to 0.5, but the colour is also interpolated to (0.5, 0, 0.5), which is a rather ugly shade of purple. And this will be rendered with 50% translucency. So the colours of texels with alpha=0 are important, because they can be "pulled in" by the filtering.

> what's the answer? Well, premultiplied alpha. All you do is before you compress, you multiply the colour channel by the alpha channel, and during rendering change blend mode from SRCALPHA:INVSRCALPHA to ONE:INVSRCALPHA. That's it - it's not rocket-science.

> So what now happens is all the alpha=0 texels are now black. Wait - but you'll get bleeding and halos! No, you don't. Let's do the half-texel example again. Let's say we have an entirely red texture, but with some bits alpha'd, and we render onto a green background. You'd expect to get shades of red, green and yellow - but the darkest yellow should be around (0.5,0.5,0) - no dark halos of something like (0.25,0.25,0), right?. So (1,0,0,1 = solid red) and (1,0,0,0 = transparent red). The second one gets premultiplied before compression to (0,0,0,0). Now we bilinear filter between them and get (0.5, 0, 0, 0.5). And then we render onto bright green (0,1,0).

> FB.rgb = texel.rgb + (1-texel.a) * FB.rgb
= (0.5, 0, 0) + (1-0.5) * (0,1,0)
= (0.5, 0, 0) + (0, 0.5, 0)
= (0.5, 0.5, 0)
> which is exactly what we were expecting.

**Comment by mm2** [comment]
> Sergey is complaining about the PRE-multiplied case. That means each colour component is multiplied by the alpha component. If alpha is zero, then the colours should be zero, any other answer is wrong. I don't see how anyone who asks for this could complain that the colour component is lost since it is exactly what they asked for.

This is the true point. If the user sends, in premultiplied alpha, an input value with alpha zero and other color components non zero then **that input value is wrong**. 

The CMM can do many things there. First thing it comes in mind is to stop and complain. Another thing would be return zeros, Another, the current implementation, would be to assume alpha is not being used at all and this is a mistake of user. Please note, if the user feeds correct values to the transform everything works as expected. Then why I should change the behaviour on wrong input values? The actual approach keeps information. Why I should return zeros? The input is wrong so the CMM answers a wrong value in the same way as input is.

> Some useful documentation on why the color does actually matter in the transparent images:

Thanks, it is very handy. And all that works perfectly fine if the input values are correct. To avoid artifacts, make sure that input alpha zero is only used on color components zero, and all will work as expected. The CMM should not be used as a way to repair wrong bitmaps.

**Comment by mrserb** [comment]
> The CMM can do many things there. First thing it comes in mind is to stop and complain. Another thing would be return zeros, Another, the current implementation, would be to assume alpha is not being used at all and this is a mistake of user. Please note, if the user feeds correct values to the transform everything works as expected. Then why I should change the behaviour on wrong input values? The actual approach keeps information. Why I should return zeros? The input is wrong so the CMM answers a wrong value in the same way as input is.

You are right that if the input in the "pre" format has an alpha=0 and other components are not null, this is a wrong/impossible value, and you can ignore division by zero, assuming that it is the user's mistake.

But take a look at the initial example in the report, the initial value passed to the CMM is all zeros [0,0,0,0] and the wrong/impossible data is produced by the CMM when it converts [0,0,0,0] to the [18, 14, 20, 0] by color transformation and then skips the alpha multiplication step. 

> Thanks, it is very handy. And all that works perfectly fine if the input values are correct. To avoid artifacts, make sure that input alpha zero is only used on color components zero, and all will work as expected. The CMM should not be used as a way to repair wrong bitmaps.

That is the problem, the CMM produces as you mention above "wrong" output on the correct input.

**Comment by mm2** [comment]
> That is the problem, the CMM produces as you mention above "wrong" output on the correct input.

Ok, I see. Do you have a sample of such profile?  So to do that you would need a transform that gives nonzero RGB values for input (0, 0, 0) and alpha on input and premultipled alpha on output, is that right?

**Comment by mrserb** [comment]
```c
int main(void) {
//    cmsSetLogErrorHandler(LogErrorHandler);
    
    cmsHPROFILE input = cmsCreate_sRGBProfile();
    cmsHPROFILE mid = cmsOpenProfileFromFile("..../PYCC.pf", "r");
    cmsHPROFILE output = cmsCreate_sRGBProfile();

    cmsHPROFILE _iccArray[20];
    int j = 0;
    _iccArray[j++] = input;

    _iccArray[j++] = mid;
    _iccArray[j++] = mid;

    _iccArray[j++] = output;

    float iRGB[3] = {0, 0, 0}, oRGB[3] = {0, 0, 0};
    cmsHTRANSFORM tx = cmsCreateMultiprofileTransform(_iccArray, j,
                            TYPE_RGB_FLT, TYPE_RGB_FLT, INTENT_PERCEPTUAL, 0);

    cmsDoTransform(tx, iRGB, oRGB, 1);
    fprintf(stderr, "r = %.3f,g = %.3f,b = %.3f,\n", oRGB[0], oRGB[1], oRGB[2]);
    
    cmsDeleteTransform(tx);
    cmsCloseProfile(input);
    cmsCloseProfile(mid);
    cmsCloseProfile(output);

    return 0;
}

```

**Comment by mrserb** [comment]
>Ok, I see. Do you have a sample of such profile? So to do that you would need a transform that gives nonzero RGB values for input (0, 0, 0) and alpha on input and premultipled alpha on output, is that right?

Yes if the RGB input is (0,0,0) as in example above and alpha is 0 as well, then for the input formats argb or argb_pre(it does not matter which since all zeros) and the output format argb_pre result is not zero.

**Comment by mrserb** [comment]
BTW I did not test the case when the output is argb_pre and the input is rgb w/o alpha, will the result be opaque?

**Comment by mm2** [comment]
Ok, so after checking several profiles & combinations I think that would be solved by forcing zeros on output when input alpha is zero. Would that be ok?

**Comment by mrserb** [comment]
Yes, But I hope that the alpha will be calculated properly before multiplcation. The new patch calculates the alpha_factor based on the output image, does it mean that the output image will always have the correct alpha? As far as I remember the littlecms does not transfer the alpha channel from opaque formats like RGB and set it to zero(not something like 1.0). It means that color conversion from RGB to RGB_PRE will result in zero colors, which is not correct. If this is an unspecified/unsupported case in the library it probably should be documented.

**Comment by mm2** [comment]
Please read the manual “engine API” on formatters-alpha channel chapter. Output premultiplied requires input alpha.
