### ISSUE TITLE
A possible overflow in cmsBuildTabulatedToneCurveFloat

### ISSUE THREAD

**Issue by hopper-vul** [mm2/Little-CMS#351]
Hi,
    we found a possible overflow in `cmsBuildTabulatedToneCurveFloat` when fuzzing.

As described in doc, for using the API `cmsBuildTabulatedToneCurveFloat`,  the parameter `nEntries` should be *the number of sample points*. However, if the passed `nEntries` is **zero**, an unintended overflow will happen in `cmsBuildTabulatedToneCurveFloat`, caused by  the following code: 
```
   Seg[2].Params[3] = values[nEntries-1];
```

Maybe it is good to ensure `nEntries` is greater than zero in `cmsBuildTabulatedToneCurveFloat` or tell people in doc that `nEntries` should be greater than zero.

Thanks for your time.

**Comment by mm2** [comment]
Fixed, thank you for reporting!

**Comment by mm2** [comment]
Fixed in 37eddd2d8787dbc5d707044cab0762bfc879fb3e
