### ISSUE TITLE
CI: Set minimal permissions to your GitHub Workflows

### ISSUE THREAD

**Issue by diogoteles08** [mm2/Little-CMS#366]
Hello!

I'm Diogo and I work on Google's Open Source Security Team([GOSST](https://github.com/diogoteles08#about-gosst-ghost)) in cooperation with the Open Source Security Foundation ([OpenSSF](https://openssf.org/)). My core job is to suggest and implement security changes on widely used open source projects 😊

I'm here to suggest the definition of minimal permissions on your workflows, as it would harden your security agains supply-chain attacks. The idea is to update your workflows to set top-level read-only permissions that would be inherited to all jobs that don't declare their permissions; and for the jobs that require any write permissions, they'd be given job-level. Defining minimal permissions would enhance security against erroneous or malicious actions from external jobs you call from your workflow. It's specially important for the case they get compromised, for example.

Setting minimum permissions for workflows is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and also by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

Please let me know what you think about this change, I'd be happy to raise a PR with it if you agree.

**Comment by diogoteles08** [comment]
Sure! I'll raise a PR shortly =)

**Comment by mm2** [comment]
Thanks for the PR, will merge it soon

**Comment by diogoteles08** [comment]
Hey Marti,
I'm coming back to this issue because seems like the changes of my PR #368 are not on the code anymore. However I looked into the commit history and there is no commit directly removing the changes. Was the removal intentional? If not, I'd be happy to raise a new PR fixing it

**Comment by mm2** [comment]
@diogoteles08
Many thanks for pointing out, I didn't notice those changes  were lost. No, it was not intentional, I assume the PR I accepted for meson build broke the file. It would be great if you could manage to setup a PR. Thanks again!
