### ISSUE TITLE
White point bug in cmsCreateRGBProfileTHR?

### ISSUE THREAD

**Issue by fnordware** [mm2/Little-CMS#39]
Profiles created using cmsCreateRGBProfileTHR() appear to always get the D50 white point, not whatever is passed in. Is this a bug?

**Comment by mm2** [comment]
Hi, thanks for reporting, No, it is not a bug, this function generates display profiles, and display profiles are required to have D50 as media white by the ICC spec in 9.2.34 "mediaWhitePointTag": "For displays, the values specified shall be those of the PCS illuminant as defined in 7.2.16."
See also Appendix D.7.7 for more info.
