### ISSUE TITLE
Suggest Adoption of Scorecard GitHub Action

### ISSUE THREAD

**Issue by diogoteles08** [mm2/Little-CMS#393]
Hey, I'm Diogo and I've raised the issues #366 and #383 contributing with some security enhancements. I'll happily continue contributing with such improvements (it's literally my job, see [my profile](https://github.com/diogoteles08/diogoteles08/blob/main/README.md#about-gosst-ghost)), but this time I come to suggest the tool that I used myself to find those security issues.

I'd like to suggest that the project add the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). The OpenSSF Scorecard uses GitHub's public API to gather public informations about your project and runs a sort of "meta-analysis" of the project's security posture. The Action then populates the project's [Security Panel](https://github.com/mm2/Little-CMS/security) with possible improvements to its security posture. It's specially helpful to ensure you won't regress on the security measures you have already adopted 😄.

Additionally, the tool integrates with the [OSV Scanner](https://security.googleblog.com/2022/12/announcing-osv-scanner-vulnerability.html), which evaluates a project's transitive dependencies looking for known vulnerabilities.

When working on the Security enhancements pointed by Scorecard, you're also able to apply for the [OpenSSF's Secure Open Source Rewards](http://sos.dev/) program, which financially rewards developers for improving the security of important open source projects

This tool is developed by the OpenSSF [in partnership with GitHub](https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/) and it's already been adopted by 1800+ projects, including [Tensorflow](https://github.com/tensorflow/tensorflow), [PyTorch](https://github.com/pytorch/pytorch), [Angular](https://github.com/angular/angular), and [Flutter](https://github.com/flutter/flutter).

If you're interested, let me know and I'll send a PR!

**Comment by diogoteles08** [comment]
Hi Marti,

> * Does this OSV Scanner need any modification on sources or  additional files other than in the .github directory?
> * Am I assumed to annotate the code to hint the compiler than those integer overflows are correct and are there because a reason? (is just an example)
> * Would the use of this tool represent to receive many mails about so called "vulnerabilities" that at the end were in test code? (I was hit badly by fuzzers)

1. No. The OSV Scanner will work as part of the Scorecard Action, analysing your repo through public GitHub APIs and showing the results at your Security Panel.

2. No, Scorecards won't require any kind of annotation -- although there is an [issue](https://github.com/ossf/scorecard/issues/1907) with this idea. After using Scorecard Action, you'll be able to dismiss any false-positives directly on the Security Panel. Then they would not bother you anymore.
3. Don't worry, the action wouldn't send you any emails haha All the notifications are intended to be shown directly on GitHub

> Otherwise I sent a mail to sos.dev about my open source project but never got any answer. Is any way to contact those guys?

I'm Sorry for that, Marti. I have some contact with the SOS team and have already contacted them. I'll get back to you as soon as I have any information.

**Comment by mm2** [comment]
Hello Diogo,

That's great. Sounds incredible powerful and non-intrusive. If you can manage to outline a quick PR I will gladly integrate this functionality.  Don't get me wrong, I toke security very seriously and any good measure to improve this is very welcome. What I want to avoid is to change code or adding spurious files just to find the whole system deprecated few years after. That already happened with Travis CI, so I'm just being a little bit more careful right now. 
Thank you so much for contacting google about the SOS team. If they are responsive, is quite probably I would hire somebody to add a decent fuzzing or just to increase overall security.

**Comment by mm2** [comment]
Hello @diogoteles08
Sorry to bother you, but after activating the scorecard all commits fail. I traced the scorecard parsing is failing with following error:

`2023/07/27 10:41:17 error processing signature: executing scorecard-api call: Post "https://api.securityscorecards.dev/projects/github.com/mm2/Little-CMS": context deadline exceeded`

Is anything I can do aside disabling scorecard? Thanks!

**Comment by mm2** [comment]
Oh, it was github's fault. Re-running the job solved the issue, sorry, just ignore the comment. Thanks!

**Comment by diogoteles08** [comment]
Hey @mm2! You're not bothering at all -- I'd be happy to get any feedback. Anyways, I'm also happy to know it worked out 😄 

Also, I'm honestly not sure it has any relation with your issue, but you might want to take a look on the possibility of [running Scorecard with an specific fine grained token](https://github.com/ossf/scorecard-action#authentication-with-fine-grained-pat-optional). Although it shouldn't change much how it's already working, I forgot to mention in this issue that this PAT is required to completely evaluating checks such `Branch-Protection` and (experimental) `Webhooks`.
