### ISSUE TITLE
Backwards incompatible API-change in 2.16

### ISSUE THREAD

**Issue by thomas-weber** [mm2/Little-CMS#429]
Hi, 
version 2.16 remove cmsGetToneCurveParams(). While the change was intentional, this has broken backward compatibility: 03020d0fdd0f8a79f275657ad1ff757fe2cc4192
The function was not documented, but nonetheless part of the public API. I see two possibilities here:

1. Re-introduce the function (maybe with a deprecation warning).
2. Bump the SONAME.

**Comment by mm2** [comment]
IMHO anything that's undocumented (and accessible) is "use at your own risk." It could go away or change at any time and is not supported. Those functions exist because testing or  other reasons but are not intended for normal operation. 

Validating this would encourage the use of other undocumented functions. And I dont want this because it means supporting bug reports, adding test cases etc.

**Comment by DominikDeak** [comment]
That's rather unfortunate. A few years ago I asked if there is a way to access the parametric constants for tone curves. I was suggested to use `cmsGetToneCurveParams`, but evidently that's no longer available in v2.16. 

https://github.com/mm2/Little-CMS/issues/218

**Comment by mm2** [comment]
Closing it as not planned

**Comment by DominikDeak** [comment]
Please don't take my above comment the wrong way. I was merely saying it's an unfortunate situation for _us_ that relied on those undocumented features. And I agree, the responsibility (and the consequences) for using private APIs rests on our shoulders. I did not intend lay blame on you or anyone for these breaking changes, other than myself.

>You were told a function would be added to development sources

>It was on testing from 2.11 to 2.16 where it finally made its way to the public API

I'm sorry, I must have missed this change in the public API. I skimmed through the ChangeLog, but I could not find notes about new features that queries Tone Curve parametric constants. I'm assuming `cmsGetToneCurveSegment` is now the correct way to get this data?

>Please remember this is open source under MIT license, basically you have the code for free but with no support. That means you need to do a check when upgrading and keep track of this kind of things. If this does not fit your needs, I would recommend to go to any commercial library.

Yes, I am fully aware. And I am actually very grateful for the effort you put into maintaining this project. Thank you!
