### ISSUE TITLE
Possible NPD in cmsCreate_OkLabProfile

### ISSUE THREAD

**Issue by rhalade** [mm2/Little-CMS#436]
Commit (https://github.com/mm2/Little-CMS/commit/f4e9f9122a001b71219d9b2d2a6ec5b8c784d785) in May 2023 added experimental support for OkLab colorspace profile. cmsCreate_OkLabProfile calls cmsCreateProfilePlaceholder but there is no null check on returned value. This bug should be fixed as is done for every other call in cmsvirt.c file.

**Comment by mm2** [comment]
Thanks for reporting. Added to wish list.

**Comment by rhalade** [comment]
https://github.com/mm2/Little-CMS/pull/437
