### ISSUE TITLE
Overflow checks in cmsCreateExtendedTransform

### ISSUE THREAD

**Issue by gal1ium** [mm2/Little-CMS#441]
Hi! 
We found a bug of missing a bound check in the API `cmsCreateExtendedTransform` at line https://github.com/mm2/Little-CMS/blob/lcms2.16/src/cmsxform.c#L1134 when `nProfiles` is 0, maybe similar to the situation at https://github.com/mm2/Little-CMS/issues/351 and https://github.com/mm2/Little-CMS/blob/lcms2.16/src/cmsxform.c#L1282

**Comment by mm2** [comment]
Thanks. It make sense to add a check to behave like other transform generators. 
Should be fixed in 46355888b823b563db928faec59b0312a05e1143
