### ISSUE TITLE
CIE XYZ D65 profile

### ISSUE THREAD

**Issue by timeinpixels** [mm2/Little-CMS#442]
Hello,

Is it possible to create CIE XYZ D65 profile with Little CMS 2?
I would like to use XYZ colorspace as an intermediate for conversions not directly supported by Little CMS or colorspaces that don't have ICC profiles.

**Comment by mm2** [comment]
Yes, it is easy. Use cmsCreateXYZProfile() to create such profile. 
If you want to have a file on the ICC, save it using cmsSaveProfileToFile. 

XYZ has no associated white point, though.

**Comment by timeinpixels** [comment]
When I am trying to create a transform from in-memory ICC to XYZ using cmsCreateXYZProfile() I get this error:

```
    if (!IsProperColorSpace(ExitColorSpace, OutputFormat)) {
        cmsSignalError(ContextID, cmsERROR_COLORSPACE_CHECK, "Wrong output color space on transform");
        return NULL;
    }
```

**Comment by mm2** [comment]
So, use XYZ as color space.
I would recommend to read the tutorial for first steps. It is in the "doc" folder.

**Comment by timeinpixels** [comment]
Apologies - I was creating a transform with TYPE_RGB_FLT instead of TYPE_XYZ_FLT - after this change it works OK. Thanks!
