### ISSUE TITLE
cmsCreateTransform returns nullptr in 2.16, but works in 2.15-

### ISSUE THREAD

**Issue by 9241304** [mm2/Little-CMS#445]
Test code (x64, VS2022)

```
#define cimg_use_png //libpng 1643
#include "cimg/CImg.h"
#include <lcms2.h>

auto src{ cil::CImg<unsigned char>("e:\\png_with_alpha.png") };
auto dst{ cil::CImg<unsigned char>(src.width(), src.height(), src.depth(), 4)};
auto inp{ cmsCreate_sRGBProfile() };
auto outp{ cmsOpenProfileFromFile("e:\\printer_profile.icm", "r") };
auto transform{ cmsCreateTransform(inp, TYPE_RGBA_8_PLANAR, outp, TYPE_CMYK_8_PLANAR, INTENT_ABSOLUTE_COLORIMETRIC, cmsFLAGS_BLACKPOINTCOMPENSATION) };
```
This works correctly in 2.15-(also checked 2.13.1), but doesn`t work in 2.16. If I remove flags, then code works in 2.16 too.

**Comment by mm2** [comment]
I've checked your code with USWebCoatedSWOP.icc and it works fine to me. Which is the printer_profile.icm you are using?

BTW, black point compensation does nothing in absolute colorimetric, but this should not make create transform to fail.

**Comment by 9241304** [comment]
I think it doesn`t matter what printer profile used. Problem appears when I set any flag. Did you check on 2.16 release version or current version?
[DTF P900 ROLL.dmp](https://github.com/mm2/Little-CMS/files/15055079/DTF.P900.ROLL.dmp)
(rename to icm)

**Comment by mm2** [comment]
Using this code with official lcms2-2.16, Visual studio 2022, works fine to me

```
#include "lcms2.h"

int main()
{
auto inp{ cmsCreate_sRGBProfile() };
auto outp{ cmsOpenProfileFromFile("DTF.P900.ROLL.dmp", "r") };
auto transform{ cmsCreateTransform(inp, TYPE_RGBA_8_PLANAR, outp, TYPE_CMYK_8_PLANAR, INTENT_ABSOLUTE_COLORIMETRIC, cmsFLAGS_BLACKPOINTCOMPENSATION) };
return 0;
}
```

**Comment by 9241304** [comment]
OK, I will build lcms2 debug version and check again.

**Comment by 9241304** [comment]
It`s a magic... I built debug version, and all works. Then rebuilt release version. And it works too.
Thanks for your time )
