### ISSUE TITLE
cmsDoTransform for 64 bit image size

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#453]
First of all, thank you so much for this wonderful library.

Secondly, have you considered supporting images greater than 2^32 pixels in size ?
This situation can arise for JPEG 2000 codec where images can be up to 2^64 pixels.
Thanks!

**Comment by mm2** [comment]
Thanks for your suggestion!
In fact it  is already done by this commit c429e374fbc1a0769af6d6516726242a7a0abfe5
Will be in the next release, if you need it now just use the unstable GIT sources.

**Comment by mm2** [comment]
Please use cmsDoTransformLineStride instead. Lines and pixels per line  must be 32 bits but the product can reach 64 bits.
This is the only way I have to allow big blocks keeping strict ABI compatibility.
