### ISSUE TITLE
TIFFTAG_TRANSFERFUNCTION values to cmsBuildTabulatedToneCurve16()

### ISSUE THREAD

**Issue by mbechard** [mm2/Little-CMS#459]
The TIFF formats says TIFFTAG_TRANSFERFUNCTION is an array of 1<< bitsPerSample entries. So 65535 for 16-bits. However cmsBuildTabulatedToneCurve16() is limited to 65530 entries.
Is this limitation necessarily? Can it be expanded so a transfer function from a 16-bit TIFF file can be consumed directly?

**Comment by mbechard** [comment]
Yes, agreed that it was a weird way for the TIFF standard to describe the transfer for 16-bit. I'm just trying to be robust in my support for TIFF reading, so while I'll output ICC, I'd like to be able to ingest the TRANSFER for 16-bit files, if that happens to be the only data that's contained in the file. A 4k 16-bit .tiff file is 65MB, so 400K isn't terrible overhead though.

Since we're only off by 5 entries though, is there no way this can be expanded?

**Comment by mm2** [comment]
400K is a huge pain for the CMM, indeed. Anyway, if you want to handle the rare case of a TIFF using that, you could just discard 5 entries on any location of the table (but the endpoints). That would make an error of 5/65536 which is 0.0076%
Not sure if this is going to work, lcms uses those entries as interpolation nodes, not just 1:1 translation. 
Anyway, remember to never create such TIFFs!

**Comment by mbechard** [comment]
Ok, thanks for the input. Appreciate your time!
