### ISSUE TITLE
cmsFormatterForColorspaceOfProfile can produce formatter with wrong number of channels

### ISSUE THREAD

**Issue by nixberg** [mm2/Little-CMS#461]
In `lcms2.h`:

```c
// NOTE THAT 'BYTES' FIELD IS SET TO ZERO ON DLB because 8 bytes overflows the bitfield
#define TYPE_XYZ_DBL          (FLOAT_SH(1)|COLORSPACE_SH(PT_XYZ)|CHANNELS_SH(3)|BYTES_SH(0))
```

In [`cmspack.c/cmsFormatterForColorspaceOfProfile`](https://github.com/mm2/Little-CMS/blob/5c54a6dedf6bebefa3a2dbbcf0164bb5616d4ba8/src/cmspack.c#L4025):

```c
// Create a fake formatter for result
return FLOAT_SH(Float) | COLORSPACE_SH(ColorSpaceBits) | BYTES_SH(nBytes) | CHANNELS_SH(nOutputChans);
```

will often produce a formatter with a wrong number of channels when `nBytes == 8`. Same with `cmsFormatterForPCSOfProfile`.

I understand that these functions aren’t documented yet and perhaps library users are expected to substitute 8 with 0 but perhaps it is an oversight.

**Comment by mm2** [comment]
Thanks, I'm adding a check for this case.
