### ISSUE TITLE
Critical issue flagged by CodeQL

### ISSUE THREAD

**Issue by boxerab** [mm2/Little-CMS#463]
Hello,
I build Little-CMS library in my codec, and I just noticed this issue flagged by CodeQL

```
[thirdparty/liblcms2/src/cmstypes.c:1103](https://github.com/GrokImageCompression/grok/blob/78e4b15b6452b5e3c52ae966bbe2061f683dc983/thirdparty/liblcms2/src/cmstypes.c#L1103-L1103)  Library
    if (!io ->Write(io, 67, Filler)) goto Error;

    // possibly add pad at the end of tag
    if(len_aligned - len_tag_requirement > 0)
Unsigned subtraction can never be negative.
```

https://github.com/GrokImageCompression/grok/security/code-scanning/118

Thanks,
Aaron

**Comment by mm2** [comment]
Thanks for reporting. CodeQL didn't see 30 lines above, 
`len_aligned = _cmsALIGNLONG(len_tag_requirement);`
This macro assures len_aligned is always greater or equal that the argument.
`#define _cmsALIGNLONG(x) (((x)+(sizeof(cmsUInt32Number)-1)) & ~(sizeof(cmsUInt32Number)-1))`
So, a false positive

**Comment by mm2** [comment]
Yes, but that's just to silence the parser and not because it's a real problem. Many times, parser developers fix these things over time. I think in this context the code is clean, if the length of tag after alignment is greater than the required length, write alignment bytes.
