### ISSUE TITLE
cmsio0.c compile error (MSVC 2013)

### ISSUE THREAD

**Issue by torokze** [mm2/Little-CMS#48]
Hello,

I have a compile error in **cmsio0.c** at line **1857**.

**error C2440: '=' : cannot convert from 'int' to 'cmsTagSignature'**

the solution to cast 0 to cmsTagSignature:

**Icc->TagNames[i] = (cmsTagSignature)0;**

Regards
Zolee

**Comment by mm2** [comment]
I cannot reproduce this anymore
