### ISSUE TITLE
Negative value returned by cmsfilelength

### ISSUE THREAD

**Issue by ya1gaurav** [mm2/Little-CMS#55]
long int CMSEXPORT cmsfilelength(FILE* f)
{
    long int p , n;

    p = ftell(f); // register current file position

    if (fseek(f, 0, SEEK_END) != 0) {
        return -1;
    }

    n = ftell(f);
    fseek(f, p, SEEK_SET); // file position restored

    return n;
}
As seen above cmsfilelength can return -1.
Also ftell can fail and return -1, so n=ftell(f) can make n as -1.
Now, cmsfilelength is used at many places to calculate length & do malloc or some other operation which may not expect negative value as input.
So, it need to change either cmsfilelength function return value or secondly wherever cmsfilelength is called, there should be check for returned size.

**Comment by mm2** [comment]
Fixed in main. Thanks for reporting.
