### ISSUE TITLE
Wrong CMSEXPORT definitions for MinGW and MSVC++

### ISSUE THREAD

**Issue by jdxAtGitHub** [mm2/Little-CMS#60]
I have just tried to build the latest Hugin's default branch using MingGW and found out that lcms2.h lacks proper CMSEXPORT definition for MinGW. The definition for MSVC++ also isn't ideal - details here: http://stackoverflow.com/questions/12511451/what-is-the-difference-between-stdcall-and-stdcal.
/J.D.

```
--- /d/Works/Hugin-MSVC/lcms2-2.7/include/lcms2.h	2015-03-17 11:19:51 +0100
+++ /d/Works/lcms2-2.7/include/lcms2.h	2015-09-17 21:28:49 +0200
@@ -219,7 +219,11 @@
 #        define CMSEXPORT       __stdcall _export
 #        define CMSAPI
 #     else
-#        define CMSEXPORT      _stdcall
+#        ifdef _MSC_VER
+#            define CMSEXPORT      __stdcall
+#        else
+#            define CMSEXPORT      __attribute__((stdcall))
+#        endif
 #        ifdef CMS_DLL_BUILD
 #            define CMSAPI    __declspec(dllexport)
 #        else
```

**Comment by mm2** [comment]
Hi,

 

Thanks for your suggestion. I was aware of the __stdcall issue, and fixed it months ago:

 

https://github.com/mm2/Little-CMS/blob/master/include/lcms2.h

 

As you can see the change you propose, already is in the GIT repository for lcms2.8

 

On the other hand, MinGW is not yet supported, it has not been tested and I cannot recommend it. I am putting MinGW support in the wish list for next release, although.

 

Regards

Marti

**Comment by mm2** [comment]
MinGW is not (yet) suported
