### ISSUE TITLE
Segfault on running sample roundtrip with ASAN

### ISSUE THREAD

**Issue by ya1gaurav** [mm2/Little-CMS#65]
Compile:
g++ -fno-omit-frame-pointer -fsanitize=address -g3 roundtrip.c -o roundtrip -I../../include/ -L../../src/.libs/ -llcms2
Run:
 ./roundtrip ../../testbed/test1.icc
ASAN:SIGSEGV
=================================================================
==10718== ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7f634eeb302c sp 0x7fff570ac170 bp 0x7fff570ac210 T0)
AddressSanitizer can not provide additional info.
==10718== WARNING: Trying to symbolize code, but external symbolizer is not initialized!
    #0 0x7f634eeb302b (/home4/Little-CMS-master/src/.libs/liblcms2.so.2+0x7002b)
    src/cmsxform.c:189
    #1 0x400f95 (/home4/Little-CMS-master/utils/samples/roundtrip+0x400f95)
    utils/samples/roundtrip.c:67
    #2 0x7f634e799ec4 (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #3 0x400a48 (/home4/Little-CMS-master/utils/samples/roundtrip+0x400a48)
==10718== ABORTING

Analysis:
It fails with test1.icc,test2.icc & bad.icc. Pass with test3.icc, test4.icc & test5.icc
It faults in dereference:
189     p -> xform(p, InputBuffer, OutputBuffer, Size, 1, &stride);

**Comment by mm2** [comment]
Fixed, thanks for pointing it out.

Regards

 

Marti Maria

The LittleCMS project

http://www.littlecms.com

**Comment by ya1gaurav** [comment]
Also, I noticed other samples are written with old code base, they need to be modified for correct working.
