### ISSUE TITLE
Virtual profiles for more color spaces?

### ISSUE THREAD

**Issue by haasn** [mm2/Little-CMS#66]
It's easy to create an RGB profile with LittleCMS, but I'm having a hard time creating a profile for more color spaces (in particular, YCbCr).

I could copy/paste the libvirt.c stuff and make some changes to adapt it from RGB to YCbCr, but some of the functions used are private/internal functions, and I'm also not sure what tags exactly LittleCMS needs internally in order to actually use the profile to transform colors, so I'm not sure how much is redundant or not for my use case.

Would it be possible to add LittleCMS functions for these kinds of profiles, in particular creating YCbCr profiles?

**Comment by mm2** [comment]
Closing old issues... this was a  functionality request, didn't pass trough at the time (2016!)
