### ISSUE TITLE
lcms writes uninitialized strings when writing named colors

### ISSUE THREAD

**Issue by thomas-weber** [mm2/Little-CMS#70]
Hi, this is Debian bug 815248, https://bugs.debian.org/815248. 
Debian is trying to move to reproducible builds (https://wiki.debian.org/ReproducibleBuilds), that is the ability to reproduce byte-identical packages.

lcms is currently using some uninitialized strings when writing named colors, leading to non-identical builds. I attach a patch that rectifies this. Please note that this is not the original patch from the above Debian bug report - the bug submitter changed some more things. Justification for these changes can be found in the bug report. I attach the original patch as well, with a "ORIG" marker in the filename.
Original patch:
[dont-write-uninitialized-memory-for-color-strings-ORIG.patch.txt](https://github.com/mm2/Little-CMS/files/193625/dont-write-uninitialized-memory-for-color-strings-ORIG.patch.txt)

Changed patch with less changes:
[dont-write-uninitialized-memory-for-color-strings.patch.txt](https://github.com/mm2/Little-CMS/files/193722/dont-write-uninitialized-memory-for-color-strings.patch.txt)

**Comment by mm2** [comment]
already fixed
