### ISSUE TITLE
Estimate/retrieve the display's luminance?

### ISSUE THREAD

**Issue by haasn** [mm2/Little-CMS#77]
Would it be possible for LittleCMS to somehow retrieve the device's “true” (output) luminance? Is there a metadata tag for this?

I know that all of the ICC profiles are, by convention, normalized to 1.0, but for my use case this is bothersome (I want to do mapping based on the true output brightness).

I could introduce the necessary correction factor myself, but this requires knowing what the display's absolute luminance is.

**Comment by mm2** [comment]
There is a metadata tag for this: cmsSigLuminanceTag. It holds the absolute luminance as XYZ value. Some monitor profiles does include this info, but it is optional.

**Comment by haasn** [comment]
Awesome, thanks! Seems that ArgyllCMS-produced profiles do contain it.

**Comment by mm2** [comment]
Sorry about the big delay... I just didnt check the git page for a big while.
Marti
