### ISSUE TITLE
undefined reference error in make check

### ISSUE THREAD

**Issue by g-coder** [mm2/Little-CMS#79]
While running make check. Getting following error:

lcms2-2.4/testbed/testcms2.c:528: undefined reference to `_cmsStageAllocIdentityCurves'
lcms2-2.4/testbed/testcms2.c:530: undefined reference to `_cmsStageAllocIdentityCurves'
lcms2-2.4/testbed/testcms2.c:541: undefined reference to `_cmsStageAllocIdentityCurves'
lcms2-2.4/testbed/testcms2.c:543: undefined reference to `_cmsStageAllocIdentityCurves'
testcms2.o: In function `CheckFormattersHalf':
lcms2-2.4/testbed/testcms2.c:4037: undefined reference to `_cmsHalf2Float'
lcms2-2.4/testbed/testcms2.c:4041: undefined reference to `_cmsFloat2Half'
testcms2.o: In function `CheckNamedColorLUT':
lcms2-2.4/testbed/testcms2.c:3412: undefined reference to `_cmsStageAllocNamedColor'
lcms2-2.4/testbed/testcms2.c:3412: undefined reference to `_cmsStageAllocNamedColor'
testcms2.o: In function `CheckLab2LabMatLUT':
lcms2-2.4/testbed/testcms2.c:3376: undefined reference to `_cmsStageAllocLab2XYZ'
lcms2-2.4/testbed/testcms2.c:3378: undefined reference to `_cmsStageAllocXYZ2Lab'
testcms2.o: In function `CheckXYZ2XYZLUT':
lcms2-2.4/testbed/testcms2.c:3358: undefined reference to `_cmsStageAllocXYZ2Lab'
lcms2-2.4/testbed/testcms2.c:3359: undefined reference to `_cmsStageAllocLab2XYZ'
testcms2.o: In function `CheckLab2LabLUT':
lcms2-2.4/testbed/testcms2.c:3341: undefined reference to `_cmsStageAllocLab2XYZ'
lcms2-2.4/testbed/testcms2.c:3342: undefined reference to `_cmsStageAllocXYZ2Lab'
testcms2.o: In function `CombineGamma16':
lcms2-2.4/testbed/testcms2.c:2664: undefined reference to `_cmsQuantizeVal'
testcms2.o: In function `ExhaustiveCheck3DinterpolationTrilinear16':
lcms2-2.4/testbed/testcms2.c:1409: undefined reference to `_cmsComputeInterpParams'
lcms2-2.4/testbed/testcms2.c:1432: undefined reference to `_cmsFreeInterpParams'
lcms2-2.4/testbed/testcms2.c:1428: undefined reference to `_cmsFreeInterpParams'
testcms2.o: In function `ExhaustiveCheck3DinterpolationTetrahedral16':
lcms2-2.4/testbed/testcms2.c:1362: undefined reference to `_cmsComputeInterpParams'
lcms2-2.4/testbed/testcms2.c:1384: undefined reference to `_cmsFreeInterpParams'
lcms2-2.4/testbed/testcms2.c:1380: undefined reference to `_cmsFreeInterpParams'
:::::::
:::::::

Please suggest how to resolve this issue.

**Comment by g-coder** [comment]
I am using version 2.4.

**Comment by mm2** [comment]
This issue is already solved. Please upgrade to 2.7 or, better, use the 2.8 which you can get in github.

**Comment by g-coder** [comment]
Can u tell me the way of compiling testcms2.c like following:
gcc testcms2.c -L<path_to_shared_lib> -llcms2 -lm -I<path_to_include_files> -o testcms2

I have tried above step but not working.

**Comment by mm2** [comment]
You could try:

 

make check

 

 

Hope that helps

Marti Maria

The LittleCMS project

http://www.littlecms.com

**Comment by g-coder** [comment]
lcms2 is written in C. But, I want to call lcms2 APIs from some .cpp file. But when I call lcms2 APIs from .cpp file then I get undefined reference errors.

**Comment by g-coder** [comment]
When are you planning the official release of version2.8?
