### ISSUE TITLE
cmsMLUsetASCII and cmsMLUsetWide write a NULL Termination but shouldn't

### ISSUE THREAD

**Issue by etrinh** [mm2/Little-CMS#81]
Hi Marti,

I noticed that cmsMLUsetASCII and cmsMLUsetWide write a Null termination in the MLU but it seems that it should not (ICC1v43_2010-12.pdf page 61).
Just removing the + 1 in len assignment solves the problem and getters look fine as they add the null termination.

Best Regards,
Eric

**Comment by mm2** [comment]
Thanks, now this is fixed.

 

Regards,

Marti Maria

The LittleCMS project

http://www.littlecms.com

**Comment by mm2** [comment]
fixed in main
