### ISSUE TITLE
tiffio.h and jpeglib.h

### ISSUE THREAD

**Issue by vperkic** [mm2/Little-CMS#90]
Hi,

Compiler shows error tiffio.h and jpeglib.h are missing and I cannot find them in files in this project.
Do you know how can I resolve this problem?

Error	17	error C1083: Cannot open include file: 'tiffio.h': No such file or directory	c:\temp\little-cms-master\utils\tificc\tifdiff.c	28	1	tiffdiff

Error	15	error C1083: Cannot open include file: 'jpeglib.h': No such file or directory	c:\temp\little-cms-master\utils\jpgicc\iccjpeg.h	20	1	jpegicc

Error	14	error C1083: Cannot open include file: 'jpeglib.h': No such file or directory	c:\temp\little-cms-master\utils\jpgicc\jpgicc.c	30	1	jpegicc

**Comment by mm2** [comment]
Please refer to documentation. In lcms api reference, the very first paragraph, requeriments-dependencies.
