### ISSUE TITLE
Swapped red and green ICC not un-swapping when soft-proofing

### ISSUE THREAD

**Issue by Beep6581** [mm2/Little-CMS#96]
Hello

RawTherapee uses LCMS, and there is work currently being done on implementing soft-proofing support.

When the output profile is set to SwappedRedAndGreen.icc, and the monitor profile is set to the same, and soft-proofing is enabled, the assumption is that the end result will be a correctly looking image. However that is not the case - when SwappedRedAndGreen.icc is set as the monitor profile, the preview image is correctly swapped, but when activating soft-proofing using that ICC as output, nothing really happens.

@mm2 do you know of any reason why that would be the case? Is there a catch?

References:
https://github.com/Beep6581/RawTherapee/issues/3406#issuecomment-242993053
https://github.com/Beep6581/RawTherapee/issues/3406#issuecomment-243305741

Kind regards

**Comment by mm2** [comment]
Hi,
It works to me, tried transicc command line:

C:\Users\mmaria\Desktop\test>transicc  -o SwappedRedAndGreen.icc -p "sRGB Color Space Profile.icm"
LittleCMS ColorSpace conversion calculator - 4.3 [LittleCMS 2.08]

Enter values, 'q' to quit
R? 0
G? 100
B? 0

R=99.9939 G=-0.1144 B=-0.0254

Maybe you are trying to softproof the appearance of SwappedRedAndGreen.icc profile? 
If so, no channel should be swapped.  The profile converts to a GRB  space and back. As long as you work in this GRB space, the image looks ok. 
*BUT* If you display the GRB numbers in a RGB space, you see the channels swapped, but this is your fault, not an issue on the profile.

Regards
Marti

**Comment by Beep6581** [comment]
I'm not sure we understood each other.

My assumption is that if I set the SwappedRedAndGreen.icc profile in RawTherapee as the monitor profile (which swaps red and green, making the image look funky) **and** as the output profile, and enable soft-proofing, then the end result will look correct, because the output profile will swap the colors once, and the monitor profile will swap them again, making the preview look correct. Is the assumption wrong?

If that assumption is wrong, how then do we check that soft-proofing is working correctly? Is there any other trick which would make this obvious, as obvious as swapped (or not swapped) color channels?

**Comment by mm2** [comment]
Ok, having read Beep6581/RawTherapee#3406 I now understand better the issue.
You are assuming that a softproofing of this profile will show swapped channels, and this is not true.
As said, the profile converts to a GRB space. The swapping occurs when you use a RGB space instead of the space that is providing the profile (GRB). But then, softproofing does not know about you are tricking.

To check soft proofing, just use any profile with small gamut. Any CMYK, like SWOP. The changes on colors are quite evident.

**Comment by Beep6581** [comment]
Thank you @mm2

**Comment by mm2** [comment]
Welcome!

**Comment by Beep6581** [comment]
By the way, I feel like I abused GitHub a bit by asking here (but its nice being able to @tag people and not register for a new account ;) ). Is there a better place to ask such questions, or is it ok with you if I used GitHub in the future?
