### ISSUE TITLE
CMS_NO_HALF_SUPPORT

### ISSUE THREAD

**Issue by dlemstra** [mm2/Little-CMS#97]
It appears that CMS_NO_HALF_SUPPORT no longer works in the latest version. The 'new' file cmsalpha.c uses functions that are not available when CMS_NO_HALF_SUPPORT is enabled (https://github.com/mm2/Little-CMS/blob/a47e96ca6539d8165c453a61a19597de56bad246/src/cmsalpha.c#L94). I am not sure if adding check for the define inside `FormatterPos` and inside the various `HLF` methods would fix this. But if that would fix it correctly I wouldn't mind sending in a pull request for it.

**Comment by mm2** [comment]
It is now fixed in https://github.com/mm2/Little-CMS/commit/23aaa8c8b136c017e622c2ce4d8ce5961bacfb8c 
thank you very much for reporting!
